// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

package com.twilioflutter.conversations.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer

private fun wrapResult(result: Any?): List<Any?> {
  return listOf(result)
}

private fun wrapError(exception: Throwable): List<Any?> {
  if (exception is FlutterError) {
    return listOf(
      exception.code,
      exception.message,
      exception.details
    )
  } else {
    return listOf(
      exception.javaClass.simpleName,
      exception.toString(),
      "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
    )
  }
}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : Throwable()

/** Client synchronization status mirrored from the Twilio Conversations SDK. */
enum class PigeonClientSynchronizationStatus(val raw: Int) {
  UNKNOWN(0),
  STARTED(1),
  CONVERSATIONSLISTCOMPLETED(2),
  COMPLETED(3),
  FAILED(4);

  companion object {
    fun ofRaw(raw: Int): PigeonClientSynchronizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Native client connection state. */
enum class PigeonClientConnectionState(val raw: Int) {
  UNKNOWN(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTED(3),
  DENIED(4),
  ERROR(5),
  FATAL(6);

  companion object {
    fun ofRaw(raw: Int): PigeonClientConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Per-conversation synchronization state. */
enum class PigeonConversationSynchronizationStatus(val raw: Int) {
  UNKNOWN(0),
  NONE(1),
  IDENTIFIER(2),
  METADATA(3),
  SYNCWINDOW(4),
  ALL(5),
  FAILED(6);

  companion object {
    fun ofRaw(raw: Int): PigeonConversationSynchronizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Discriminator for events emitted from native code to Dart. */
enum class PigeonConversationsEventType(val raw: Int) {
  CLIENTSYNCHRONIZATIONSTATUSUPDATED(0),
  CONNECTIONSTATECHANGED(1),
  CONVERSATIONADDED(2),
  CONVERSATIONUPDATED(3),
  CONVERSATIONDELETED(4),
  CONVERSATIONSYNCHRONIZATIONUPDATED(5),
  MESSAGEADDED(6),
  MESSAGEUPDATED(7),
  MESSAGEDELETED(8),
  PARTICIPANTADDED(9),
  PARTICIPANTUPDATED(10),
  PARTICIPANTDELETED(11),
  TYPINGSTARTED(12),
  TYPINGENDED(13),
  USERUPDATED(14),
  USERSUBSCRIBED(15),
  USERUNSUBSCRIBED(16),
  TOKENABOUTTOEXPIRE(17),
  TOKENEXPIRED(18),
  NOTIFICATIONSUBSCRIBED(19),
  ERROR(20);

  companion object {
    fun ofRaw(raw: Int): PigeonConversationsEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class PigeonMessageContentType(val raw: Int) {
  TEXT(0),
  MEDIA(1);

  companion object {
    fun ofRaw(raw: Int): PigeonMessageContentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonConnectRequest (
  val accessToken: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonConnectRequest {
      val accessToken = list[0] as String
      return PigeonConnectRequest(accessToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      accessToken,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonConversationDto (
  val sid: String,
  val uniqueName: String,
  val friendlyName: String,
  val lastMessageIndex: Long? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonConversationDto {
      val sid = list[0] as String
      val uniqueName = list[1] as String
      val friendlyName = list[2] as String
      val lastMessageIndex = list[3].let { if (it is Int) it.toLong() else it as Long? }
      return PigeonConversationDto(sid, uniqueName, friendlyName, lastMessageIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonMediaAttachmentDto (
  val sid: String,
  val contentType: String,
  val filename: String,
  val sizeBytes: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonMediaAttachmentDto {
      val sid = list[0] as String
      val contentType = list[1] as String
      val filename = list[2] as String
      val sizeBytes = list[3].let { if (it is Int) it.toLong() else it as Long }
      return PigeonMediaAttachmentDto(sid, contentType, filename, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sid,
      contentType,
      filename,
      sizeBytes,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonMessageDto (
  val sid: String,
  val conversationSid: String,
  val author: String,
  val body: String,
  val messageIndex: Long,
  val dateCreatedEpochMs: Long,
  val contentType: PigeonMessageContentType,
  val mediaAttachments: List<PigeonMediaAttachmentDto?>? = null,
  val attributesJson: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonMessageDto {
      val sid = list[0] as String
      val conversationSid = list[1] as String
      val author = list[2] as String
      val body = list[3] as String
      val messageIndex = list[4].let { if (it is Int) it.toLong() else it as Long }
      val dateCreatedEpochMs = list[5].let { if (it is Int) it.toLong() else it as Long }
      val contentType = PigeonMessageContentType.ofRaw(list[6] as Int)!!
      val mediaAttachments = list[7] as List<PigeonMediaAttachmentDto?>?
      val attributesJson = list[8] as String?
      return PigeonMessageDto(sid, conversationSid, author, body, messageIndex, dateCreatedEpochMs, contentType, mediaAttachments, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType.raw,
      mediaAttachments,
      attributesJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonParticipantDto (
  val sid: String,
  val identity: String,
  val conversationSid: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonParticipantDto {
      val sid = list[0] as String
      val identity = list[1] as String
      val conversationSid = list[2] as String
      return PigeonParticipantDto(sid, identity, conversationSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      sid,
      identity,
      conversationSid,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonUserDto (
  val identity: String,
  val friendlyName: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonUserDto {
      val identity = list[0] as String
      val friendlyName = list[1] as String?
      return PigeonUserDto(identity, friendlyName)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      identity,
      friendlyName,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonSendMessageRequest (
  val conversationSid: String,
  val body: String,
  val attributesJson: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonSendMessageRequest {
      val conversationSid = list[0] as String
      val body = list[1] as String
      val attributesJson = list[2] as String?
      return PigeonSendMessageRequest(conversationSid, body, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
      body,
      attributesJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonGetMessagesRequest (
  val conversationSid: String,
  val count: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonGetMessagesRequest {
      val conversationSid = list[0] as String
      val count = list[1].let { if (it is Int) it.toLong() else it as Long }
      return PigeonGetMessagesRequest(conversationSid, count)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
      count,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonGetMessagesBeforeRequest (
  val conversationSid: String,
  val beforeMessageIndex: Long,
  val count: Long

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonGetMessagesBeforeRequest {
      val conversationSid = list[0] as String
      val beforeMessageIndex = list[1].let { if (it is Int) it.toLong() else it as Long }
      val count = list[2].let { if (it is Int) it.toLong() else it as Long }
      return PigeonGetMessagesBeforeRequest(conversationSid, beforeMessageIndex, count)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
      beforeMessageIndex,
      count,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonSendMediaMessageRequest (
  val conversationSid: String,
  val filePath: String,
  val mimeType: String,
  val filename: String,
  val caption: String? = null,
  val attributesJson: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonSendMediaMessageRequest {
      val conversationSid = list[0] as String
      val filePath = list[1] as String
      val mimeType = list[2] as String
      val filename = list[3] as String
      val caption = list[4] as String?
      val attributesJson = list[5] as String?
      return PigeonSendMediaMessageRequest(conversationSid, filePath, mimeType, filename, caption, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonGetMediaTemporaryUrlRequest (
  val conversationSid: String,
  val messageIndex: Long,
  val mediaSid: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonGetMediaTemporaryUrlRequest {
      val conversationSid = list[0] as String
      val messageIndex = list[1].let { if (it is Int) it.toLong() else it as Long }
      val mediaSid = list[2] as String
      return PigeonGetMediaTemporaryUrlRequest(conversationSid, messageIndex, mediaSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
      messageIndex,
      mediaSid,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonConversationRequest (
  val conversationSid: String

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonConversationRequest {
      val conversationSid = list[0] as String
      return PigeonConversationRequest(conversationSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      conversationSid,
    )
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class PigeonConversationsNativeEvent (
  val type: PigeonConversationsEventType,
  val synchronizationStatus: PigeonClientSynchronizationStatus? = null,
  val connectionState: PigeonClientConnectionState? = null,
  val conversationSyncStatus: PigeonConversationSynchronizationStatus? = null,
  val conversation: PigeonConversationDto? = null,
  val message: PigeonMessageDto? = null,
  val participant: PigeonParticipantDto? = null,
  val user: PigeonUserDto? = null,
  val updateReason: String? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null

) {
  companion object {
    @Suppress("UNCHECKED_CAST")
    fun fromList(list: List<Any?>): PigeonConversationsNativeEvent {
      val type = PigeonConversationsEventType.ofRaw(list[0] as Int)!!
      val synchronizationStatus: PigeonClientSynchronizationStatus? = (list[1] as Int?)?.let {
        PigeonClientSynchronizationStatus.ofRaw(it)
      }
      val connectionState: PigeonClientConnectionState? = (list[2] as Int?)?.let {
        PigeonClientConnectionState.ofRaw(it)
      }
      val conversationSyncStatus: PigeonConversationSynchronizationStatus? = (list[3] as Int?)?.let {
        PigeonConversationSynchronizationStatus.ofRaw(it)
      }
      val conversation: PigeonConversationDto? = (list[4] as List<Any?>?)?.let {
        PigeonConversationDto.fromList(it)
      }
      val message: PigeonMessageDto? = (list[5] as List<Any?>?)?.let {
        PigeonMessageDto.fromList(it)
      }
      val participant: PigeonParticipantDto? = (list[6] as List<Any?>?)?.let {
        PigeonParticipantDto.fromList(it)
      }
      val user: PigeonUserDto? = (list[7] as List<Any?>?)?.let {
        PigeonUserDto.fromList(it)
      }
      val updateReason = list[8] as String?
      val errorCode = list[9] as String?
      val errorMessage = list[10] as String?
      return PigeonConversationsNativeEvent(type, synchronizationStatus, connectionState, conversationSyncStatus, conversation, message, participant, user, updateReason, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf<Any?>(
      type.raw,
      synchronizationStatus?.raw,
      connectionState?.raw,
      conversationSyncStatus?.raw,
      conversation?.toList(),
      message?.toList(),
      participant?.toList(),
      user?.toList(),
      updateReason,
      errorCode,
      errorMessage,
    )
  }
}

@Suppress("UNCHECKED_CAST")
private object TwilioConversationsHostApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonConnectRequest.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonConversationDto.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonConversationRequest.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonGetMediaTemporaryUrlRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonGetMessagesBeforeRequest.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonGetMessagesRequest.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonMediaAttachmentDto.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonMessageDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonParticipantDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonSendMediaMessageRequest.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonSendMessageRequest.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonConnectRequest -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PigeonConversationDto -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PigeonConversationRequest -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PigeonGetMediaTemporaryUrlRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PigeonGetMessagesBeforeRequest -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PigeonGetMessagesRequest -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is PigeonMediaAttachmentDto -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is PigeonMessageDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is PigeonParticipantDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is PigeonSendMediaMessageRequest -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is PigeonSendMessageRequest -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TwilioConversationsHostApi {
  fun connect(request: PigeonConnectRequest, callback: (Result<Unit>) -> Unit)
  fun disconnect(callback: (Result<Unit>) -> Unit)
  fun updateAccessToken(accessToken: String, callback: (Result<Unit>) -> Unit)
  fun sendMessage(request: PigeonSendMessageRequest, callback: (Result<PigeonMessageDto>) -> Unit)
  fun listConversations(callback: (Result<List<PigeonConversationDto>>) -> Unit)
  fun getConversation(sidOrUniqueName: String, callback: (Result<PigeonConversationDto>) -> Unit)
  fun getLastMessages(request: PigeonGetMessagesRequest, callback: (Result<List<PigeonMessageDto>>) -> Unit)
  fun getMessagesBefore(request: PigeonGetMessagesBeforeRequest, callback: (Result<List<PigeonMessageDto>>) -> Unit)
  fun sendMediaMessage(request: PigeonSendMediaMessageRequest, callback: (Result<PigeonMessageDto>) -> Unit)
  fun getMediaTemporaryUrl(request: PigeonGetMediaTemporaryUrlRequest, callback: (Result<String>) -> Unit)
  fun getParticipants(request: PigeonConversationRequest, callback: (Result<List<PigeonParticipantDto>>) -> Unit)
  fun sendTyping(request: PigeonConversationRequest, callback: (Result<Unit>) -> Unit)

  companion object {
    /** The codec used by TwilioConversationsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      TwilioConversationsHostApiCodec
    }
    /** Sets up an instance of `TwilioConversationsHostApi` to handle messages through the `binaryMessenger`. */
    @Suppress("UNCHECKED_CAST")
    fun setUp(binaryMessenger: BinaryMessenger, api: TwilioConversationsHostApi?) {
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonConnectRequest
            api.connect(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.disconnect() { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accessTokenArg = args[0] as String
            api.updateAccessToken(accessTokenArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonSendMessageRequest
            api.sendMessage(requestArg) { result: Result<PigeonMessageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            api.listConversations() { result: Result<List<PigeonConversationDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sidOrUniqueNameArg = args[0] as String
            api.getConversation(sidOrUniqueNameArg) { result: Result<PigeonConversationDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonGetMessagesRequest
            api.getLastMessages(requestArg) { result: Result<List<PigeonMessageDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonGetMessagesBeforeRequest
            api.getMessagesBefore(requestArg) { result: Result<List<PigeonMessageDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonSendMediaMessageRequest
            api.sendMediaMessage(requestArg) { result: Result<PigeonMessageDto> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonGetMediaTemporaryUrlRequest
            api.getMediaTemporaryUrl(requestArg) { result: Result<String> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonConversationRequest
            api.getParticipants(requestArg) { result: Result<List<PigeonParticipantDto>> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                val data = result.getOrNull()
                reply.reply(wrapResult(data))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as PigeonConversationRequest
            api.sendTyping(requestArg) { result: Result<Unit> ->
              val error = result.exceptionOrNull()
              if (error != null) {
                reply.reply(wrapError(error))
              } else {
                reply.reply(wrapResult(null))
              }
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
@Suppress("UNCHECKED_CAST")
private object TwilioConversationsFlutterApiCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      128.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonConversationDto.fromList(it)
        }
      }
      129.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonConversationsNativeEvent.fromList(it)
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonMediaAttachmentDto.fromList(it)
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonMessageDto.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonParticipantDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          PigeonUserDto.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is PigeonConversationDto -> {
        stream.write(128)
        writeValue(stream, value.toList())
      }
      is PigeonConversationsNativeEvent -> {
        stream.write(129)
        writeValue(stream, value.toList())
      }
      is PigeonMediaAttachmentDto -> {
        stream.write(130)
        writeValue(stream, value.toList())
      }
      is PigeonMessageDto -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is PigeonParticipantDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is PigeonUserDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}

/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
@Suppress("UNCHECKED_CAST")
class TwilioConversationsFlutterApi(private val binaryMessenger: BinaryMessenger) {
  companion object {
    /** The codec used by TwilioConversationsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      TwilioConversationsFlutterApiCodec
    }
  }
  fun onNativeEvent(eventArg: PigeonConversationsNativeEvent, callback: () -> Unit) {
    val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent", codec)
    channel.send(listOf(eventArg)) {
      callback()
    }
  }
}
