// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.twilioflutter.conversations.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object ConversationsPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

/** Client synchronization status mirrored from the Twilio Conversations SDK. */
enum class ClientSynchronizationStatus(val raw: Int) {
  UNKNOWN(0),
  STARTED(1),
  CONVERSATIONS_LIST_COMPLETED(2),
  COMPLETED(3),
  FAILED(4);

  companion object {
    fun ofRaw(raw: Int): ClientSynchronizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Native client connection state. */
enum class ClientConnectionState(val raw: Int) {
  UNKNOWN(0),
  CONNECTING(1),
  CONNECTED(2),
  DISCONNECTED(3),
  DENIED(4),
  ERROR(5),
  FATAL(6);

  companion object {
    fun ofRaw(raw: Int): ClientConnectionState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Per-conversation synchronization state. */
enum class ConversationSynchronizationStatus(val raw: Int) {
  UNKNOWN(0),
  NONE(1),
  IDENTIFIER(2),
  METADATA(3),
  SYNC_WINDOW(4),
  ALL(5),
  FAILED(6);

  companion object {
    fun ofRaw(raw: Int): ConversationSynchronizationStatus? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Discriminator for events emitted from native code to Dart. */
enum class ConversationsEventType(val raw: Int) {
  CLIENT_SYNCHRONIZATION_STATUS_UPDATED(0),
  CONNECTION_STATE_CHANGED(1),
  CONVERSATION_ADDED(2),
  CONVERSATION_UPDATED(3),
  CONVERSATION_DELETED(4),
  CONVERSATION_SYNCHRONIZATION_UPDATED(5),
  MESSAGE_ADDED(6),
  MESSAGE_UPDATED(7),
  MESSAGE_DELETED(8),
  PARTICIPANT_ADDED(9),
  PARTICIPANT_UPDATED(10),
  PARTICIPANT_DELETED(11),
  TYPING_STARTED(12),
  TYPING_ENDED(13),
  USER_UPDATED(14),
  USER_SUBSCRIBED(15),
  USER_UNSUBSCRIBED(16),
  TOKEN_ABOUT_TO_EXPIRE(17),
  TOKEN_EXPIRED(18),
  NOTIFICATION_SUBSCRIBED(19),
  ERROR(20);

  companion object {
    fun ofRaw(raw: Int): ConversationsEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class MessageContentType(val raw: Int) {
  TEXT(0),
  MEDIA(1);

  companion object {
    fun ofRaw(raw: Int): MessageContentType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConnectRequest (
  val accessToken: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConnectRequest {
      val accessToken = pigeonVar_list[0] as String
      return ConnectRequest(accessToken)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConnectRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.accessToken, other.accessToken)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.accessToken)
    return result
  }
  override fun toString(): String {
    return "ConnectRequest(accessToken=$accessToken)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationDto (
  val sid: String,
  val uniqueName: String,
  val friendlyName: String,
  val lastMessageIndex: Long? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationDto {
      val sid = pigeonVar_list[0] as String
      val uniqueName = pigeonVar_list[1] as String
      val friendlyName = pigeonVar_list[2] as String
      val lastMessageIndex = pigeonVar_list[3] as Long?
      return ConversationDto(sid, uniqueName, friendlyName, lastMessageIndex)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConversationDto
    return ConversationsPigeonPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsPigeonPigeonUtils.deepEquals(this.uniqueName, other.uniqueName) && ConversationsPigeonPigeonUtils.deepEquals(this.friendlyName, other.friendlyName) && ConversationsPigeonPigeonUtils.deepEquals(this.lastMessageIndex, other.lastMessageIndex)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.uniqueName)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.friendlyName)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.lastMessageIndex)
    return result
  }
  override fun toString(): String {
    return "ConversationDto(sid=$sid, uniqueName=$uniqueName, friendlyName=$friendlyName, lastMessageIndex=$lastMessageIndex)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MediaAttachmentDto (
  val sid: String,
  val contentType: String,
  val filename: String,
  val sizeBytes: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MediaAttachmentDto {
      val sid = pigeonVar_list[0] as String
      val contentType = pigeonVar_list[1] as String
      val filename = pigeonVar_list[2] as String
      val sizeBytes = pigeonVar_list[3] as Long
      return MediaAttachmentDto(sid, contentType, filename, sizeBytes)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      contentType,
      filename,
      sizeBytes,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MediaAttachmentDto
    return ConversationsPigeonPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsPigeonPigeonUtils.deepEquals(this.contentType, other.contentType) && ConversationsPigeonPigeonUtils.deepEquals(this.filename, other.filename) && ConversationsPigeonPigeonUtils.deepEquals(this.sizeBytes, other.sizeBytes)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.contentType)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.filename)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.sizeBytes)
    return result
  }
  override fun toString(): String {
    return "MediaAttachmentDto(sid=$sid, contentType=$contentType, filename=$filename, sizeBytes=$sizeBytes)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class MessageDto (
  val sid: String,
  val conversationSid: String,
  val author: String,
  val body: String,
  val messageIndex: Long,
  val dateCreatedEpochMs: Long,
  val contentType: MessageContentType,
  val mediaAttachments: List<MediaAttachmentDto?>? = null,
  val attributesJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): MessageDto {
      val sid = pigeonVar_list[0] as String
      val conversationSid = pigeonVar_list[1] as String
      val author = pigeonVar_list[2] as String
      val body = pigeonVar_list[3] as String
      val messageIndex = pigeonVar_list[4] as Long
      val dateCreatedEpochMs = pigeonVar_list[5] as Long
      val contentType = pigeonVar_list[6] as MessageContentType
      val mediaAttachments = pigeonVar_list[7] as List<MediaAttachmentDto?>?
      val attributesJson = pigeonVar_list[8] as String?
      return MessageDto(sid, conversationSid, author, body, messageIndex, dateCreatedEpochMs, contentType, mediaAttachments, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType,
      mediaAttachments,
      attributesJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as MessageDto
    return ConversationsPigeonPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.author, other.author) && ConversationsPigeonPigeonUtils.deepEquals(this.body, other.body) && ConversationsPigeonPigeonUtils.deepEquals(this.messageIndex, other.messageIndex) && ConversationsPigeonPigeonUtils.deepEquals(this.dateCreatedEpochMs, other.dateCreatedEpochMs) && ConversationsPigeonPigeonUtils.deepEquals(this.contentType, other.contentType) && ConversationsPigeonPigeonUtils.deepEquals(this.mediaAttachments, other.mediaAttachments) && ConversationsPigeonPigeonUtils.deepEquals(this.attributesJson, other.attributesJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.author)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.body)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.messageIndex)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.dateCreatedEpochMs)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.contentType)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.mediaAttachments)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.attributesJson)
    return result
  }
  override fun toString(): String {
    return "MessageDto(sid=$sid, conversationSid=$conversationSid, author=$author, body=$body, messageIndex=$messageIndex, dateCreatedEpochMs=$dateCreatedEpochMs, contentType=$contentType, mediaAttachments=$mediaAttachments, attributesJson=$attributesJson)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ParticipantDto (
  val sid: String,
  val identity: String,
  val conversationSid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ParticipantDto {
      val sid = pigeonVar_list[0] as String
      val identity = pigeonVar_list[1] as String
      val conversationSid = pigeonVar_list[2] as String
      return ParticipantDto(sid, identity, conversationSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      identity,
      conversationSid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ParticipantDto
    return ConversationsPigeonPigeonUtils.deepEquals(this.sid, other.sid) && ConversationsPigeonPigeonUtils.deepEquals(this.identity, other.identity) && ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.identity)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    return result
  }
  override fun toString(): String {
    return "ParticipantDto(sid=$sid, identity=$identity, conversationSid=$conversationSid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class UserDto (
  val identity: String,
  val friendlyName: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): UserDto {
      val identity = pigeonVar_list[0] as String
      val friendlyName = pigeonVar_list[1] as String?
      return UserDto(identity, friendlyName)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      identity,
      friendlyName,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as UserDto
    return ConversationsPigeonPigeonUtils.deepEquals(this.identity, other.identity) && ConversationsPigeonPigeonUtils.deepEquals(this.friendlyName, other.friendlyName)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.identity)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.friendlyName)
    return result
  }
  override fun toString(): String {
    return "UserDto(identity=$identity, friendlyName=$friendlyName)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SendMessageRequest (
  val conversationSid: String,
  val body: String,
  val attributesJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SendMessageRequest {
      val conversationSid = pigeonVar_list[0] as String
      val body = pigeonVar_list[1] as String
      val attributesJson = pigeonVar_list[2] as String?
      return SendMessageRequest(conversationSid, body, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      body,
      attributesJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SendMessageRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.body, other.body) && ConversationsPigeonPigeonUtils.deepEquals(this.attributesJson, other.attributesJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.body)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.attributesJson)
    return result
  }
  override fun toString(): String {
    return "SendMessageRequest(conversationSid=$conversationSid, body=$body, attributesJson=$attributesJson)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetMessagesRequest (
  val conversationSid: String,
  val count: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetMessagesRequest {
      val conversationSid = pigeonVar_list[0] as String
      val count = pigeonVar_list[1] as Long
      return GetMessagesRequest(conversationSid, count)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      count,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetMessagesRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.count, other.count)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.count)
    return result
  }
  override fun toString(): String {
    return "GetMessagesRequest(conversationSid=$conversationSid, count=$count)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetMessagesBeforeRequest (
  val conversationSid: String,
  val beforeMessageIndex: Long,
  val count: Long
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetMessagesBeforeRequest {
      val conversationSid = pigeonVar_list[0] as String
      val beforeMessageIndex = pigeonVar_list[1] as Long
      val count = pigeonVar_list[2] as Long
      return GetMessagesBeforeRequest(conversationSid, beforeMessageIndex, count)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      beforeMessageIndex,
      count,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetMessagesBeforeRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.beforeMessageIndex, other.beforeMessageIndex) && ConversationsPigeonPigeonUtils.deepEquals(this.count, other.count)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.beforeMessageIndex)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.count)
    return result
  }
  override fun toString(): String {
    return "GetMessagesBeforeRequest(conversationSid=$conversationSid, beforeMessageIndex=$beforeMessageIndex, count=$count)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class SendMediaMessageRequest (
  val conversationSid: String,
  val filePath: String,
  val mimeType: String,
  val filename: String,
  val caption: String? = null,
  val attributesJson: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): SendMediaMessageRequest {
      val conversationSid = pigeonVar_list[0] as String
      val filePath = pigeonVar_list[1] as String
      val mimeType = pigeonVar_list[2] as String
      val filename = pigeonVar_list[3] as String
      val caption = pigeonVar_list[4] as String?
      val attributesJson = pigeonVar_list[5] as String?
      return SendMediaMessageRequest(conversationSid, filePath, mimeType, filename, caption, attributesJson)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as SendMediaMessageRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.filePath, other.filePath) && ConversationsPigeonPigeonUtils.deepEquals(this.mimeType, other.mimeType) && ConversationsPigeonPigeonUtils.deepEquals(this.filename, other.filename) && ConversationsPigeonPigeonUtils.deepEquals(this.caption, other.caption) && ConversationsPigeonPigeonUtils.deepEquals(this.attributesJson, other.attributesJson)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.filePath)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.mimeType)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.filename)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.caption)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.attributesJson)
    return result
  }
  override fun toString(): String {
    return "SendMediaMessageRequest(conversationSid=$conversationSid, filePath=$filePath, mimeType=$mimeType, filename=$filename, caption=$caption, attributesJson=$attributesJson)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class GetMediaTemporaryUrlRequest (
  val conversationSid: String,
  val messageIndex: Long,
  val mediaSid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): GetMediaTemporaryUrlRequest {
      val conversationSid = pigeonVar_list[0] as String
      val messageIndex = pigeonVar_list[1] as Long
      val mediaSid = pigeonVar_list[2] as String
      return GetMediaTemporaryUrlRequest(conversationSid, messageIndex, mediaSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
      messageIndex,
      mediaSid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as GetMediaTemporaryUrlRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid) && ConversationsPigeonPigeonUtils.deepEquals(this.messageIndex, other.messageIndex) && ConversationsPigeonPigeonUtils.deepEquals(this.mediaSid, other.mediaSid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.messageIndex)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.mediaSid)
    return result
  }
  override fun toString(): String {
    return "GetMediaTemporaryUrlRequest(conversationSid=$conversationSid, messageIndex=$messageIndex, mediaSid=$mediaSid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationRequest (
  val conversationSid: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationRequest {
      val conversationSid = pigeonVar_list[0] as String
      return ConversationRequest(conversationSid)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      conversationSid,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConversationRequest
    return ConversationsPigeonPigeonUtils.deepEquals(this.conversationSid, other.conversationSid)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSid)
    return result
  }
  override fun toString(): String {
    return "ConversationRequest(conversationSid=$conversationSid)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class ConversationsNativeEvent (
  val type: ConversationsEventType,
  val synchronizationStatus: ClientSynchronizationStatus? = null,
  val connectionState: ClientConnectionState? = null,
  val conversationSyncStatus: ConversationSynchronizationStatus? = null,
  val conversation: ConversationDto? = null,
  val message: MessageDto? = null,
  val participant: ParticipantDto? = null,
  val user: UserDto? = null,
  val updateReason: String? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): ConversationsNativeEvent {
      val type = pigeonVar_list[0] as ConversationsEventType
      val synchronizationStatus = pigeonVar_list[1] as ClientSynchronizationStatus?
      val connectionState = pigeonVar_list[2] as ClientConnectionState?
      val conversationSyncStatus = pigeonVar_list[3] as ConversationSynchronizationStatus?
      val conversation = pigeonVar_list[4] as ConversationDto?
      val message = pigeonVar_list[5] as MessageDto?
      val participant = pigeonVar_list[6] as ParticipantDto?
      val user = pigeonVar_list[7] as UserDto?
      val updateReason = pigeonVar_list[8] as String?
      val errorCode = pigeonVar_list[9] as String?
      val errorMessage = pigeonVar_list[10] as String?
      return ConversationsNativeEvent(type, synchronizationStatus, connectionState, conversationSyncStatus, conversation, message, participant, user, updateReason, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      synchronizationStatus,
      connectionState,
      conversationSyncStatus,
      conversation,
      message,
      participant,
      user,
      updateReason,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as ConversationsNativeEvent
    return ConversationsPigeonPigeonUtils.deepEquals(this.type, other.type) && ConversationsPigeonPigeonUtils.deepEquals(this.synchronizationStatus, other.synchronizationStatus) && ConversationsPigeonPigeonUtils.deepEquals(this.connectionState, other.connectionState) && ConversationsPigeonPigeonUtils.deepEquals(this.conversationSyncStatus, other.conversationSyncStatus) && ConversationsPigeonPigeonUtils.deepEquals(this.conversation, other.conversation) && ConversationsPigeonPigeonUtils.deepEquals(this.message, other.message) && ConversationsPigeonPigeonUtils.deepEquals(this.participant, other.participant) && ConversationsPigeonPigeonUtils.deepEquals(this.user, other.user) && ConversationsPigeonPigeonUtils.deepEquals(this.updateReason, other.updateReason) && ConversationsPigeonPigeonUtils.deepEquals(this.errorCode, other.errorCode) && ConversationsPigeonPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.type)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.synchronizationStatus)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.connectionState)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversationSyncStatus)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.conversation)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.message)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.participant)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.user)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.updateReason)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + ConversationsPigeonPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "ConversationsNativeEvent(type=$type, synchronizationStatus=$synchronizationStatus, connectionState=$connectionState, conversationSyncStatus=$conversationSyncStatus, conversation=$conversation, message=$message, participant=$participant, user=$user, updateReason=$updateReason, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class ConversationsPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ClientSynchronizationStatus.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ClientConnectionState.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConversationSynchronizationStatus.ofRaw(it.toInt())
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          ConversationsEventType.ofRaw(it.toInt())
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          MessageContentType.ofRaw(it.toInt())
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConnectRequest.fromList(it)
        }
      }
      135.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationDto.fromList(it)
        }
      }
      136.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MediaAttachmentDto.fromList(it)
        }
      }
      137.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          MessageDto.fromList(it)
        }
      }
      138.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ParticipantDto.fromList(it)
        }
      }
      139.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          UserDto.fromList(it)
        }
      }
      140.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SendMessageRequest.fromList(it)
        }
      }
      141.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetMessagesRequest.fromList(it)
        }
      }
      142.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetMessagesBeforeRequest.fromList(it)
        }
      }
      143.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          SendMediaMessageRequest.fromList(it)
        }
      }
      144.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          GetMediaTemporaryUrlRequest.fromList(it)
        }
      }
      145.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationRequest.fromList(it)
        }
      }
      146.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          ConversationsNativeEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is ClientSynchronizationStatus -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is ClientConnectionState -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is ConversationSynchronizationStatus -> {
        stream.write(131)
        writeValue(stream, value.raw.toLong())
      }
      is ConversationsEventType -> {
        stream.write(132)
        writeValue(stream, value.raw.toLong())
      }
      is MessageContentType -> {
        stream.write(133)
        writeValue(stream, value.raw.toLong())
      }
      is ConnectRequest -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      is ConversationDto -> {
        stream.write(135)
        writeValue(stream, value.toList())
      }
      is MediaAttachmentDto -> {
        stream.write(136)
        writeValue(stream, value.toList())
      }
      is MessageDto -> {
        stream.write(137)
        writeValue(stream, value.toList())
      }
      is ParticipantDto -> {
        stream.write(138)
        writeValue(stream, value.toList())
      }
      is UserDto -> {
        stream.write(139)
        writeValue(stream, value.toList())
      }
      is SendMessageRequest -> {
        stream.write(140)
        writeValue(stream, value.toList())
      }
      is GetMessagesRequest -> {
        stream.write(141)
        writeValue(stream, value.toList())
      }
      is GetMessagesBeforeRequest -> {
        stream.write(142)
        writeValue(stream, value.toList())
      }
      is SendMediaMessageRequest -> {
        stream.write(143)
        writeValue(stream, value.toList())
      }
      is GetMediaTemporaryUrlRequest -> {
        stream.write(144)
        writeValue(stream, value.toList())
      }
      is ConversationRequest -> {
        stream.write(145)
        writeValue(stream, value.toList())
      }
      is ConversationsNativeEvent -> {
        stream.write(146)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TwilioConversationsHostApi {
  suspend fun connect(request: ConnectRequest)
  suspend fun disconnect()
  suspend fun updateAccessToken(accessToken: String)
  suspend fun sendMessage(request: SendMessageRequest): MessageDto
  suspend fun listConversations(): List<ConversationDto>
  suspend fun getConversation(sidOrUniqueName: String): ConversationDto
  suspend fun getLastMessages(request: GetMessagesRequest): List<MessageDto>
  suspend fun getMessagesBefore(request: GetMessagesBeforeRequest): List<MessageDto>
  suspend fun sendMediaMessage(request: SendMediaMessageRequest): MessageDto
  suspend fun getMediaTemporaryUrl(request: GetMediaTemporaryUrlRequest): String
  suspend fun getParticipants(request: ConversationRequest): List<ParticipantDto>
  suspend fun sendTyping(request: ConversationRequest)

  companion object {
    /** The codec used by TwilioConversationsHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      ConversationsPigeonPigeonCodec()
    }
    /** Sets up an instance of `TwilioConversationsHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TwilioConversationsHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ConnectRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.connect(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disconnect()
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val accessTokenArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.updateAccessToken(accessTokenArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SendMessageRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendMessage(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.listConversations())
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val sidOrUniqueNameArg = args[0] as String
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getConversation(sidOrUniqueNameArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as GetMessagesRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getLastMessages(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as GetMessagesBeforeRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMessagesBefore(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as SendMediaMessageRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.sendMediaMessage(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as GetMediaTemporaryUrlRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getMediaTemporaryUrl(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ConversationRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                listOf(api.getParticipants(requestArg))
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as ConversationRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.sendTyping(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                ConversationsPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TwilioConversationsFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TwilioConversationsFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      ConversationsPigeonPigeonCodec()
    }
  }
  suspend fun onNativeEvent(eventArg: ConversationsNativeEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(ConversationsPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
