// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: public_member_api_docs, non_constant_identifier_names, avoid_as, unused_import, unnecessary_parenthesis, prefer_null_aware_operators, omit_local_variable_types, unused_shown_name, unnecessary_import

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List, Uint8List;

import 'package:flutter/foundation.dart' show ReadBuffer, WriteBuffer;
import 'package:flutter/services.dart';

/// Client synchronization status mirrored from the Twilio Conversations SDK.
enum PigeonClientSynchronizationStatus {
  unknown,
  started,
  conversationsListCompleted,
  completed,
  failed,
}

/// Native client connection state.
enum PigeonClientConnectionState {
  unknown,
  connecting,
  connected,
  disconnected,
  denied,
  error,
  fatal,
}

/// Per-conversation synchronization state.
enum PigeonConversationSynchronizationStatus {
  unknown,
  none,
  identifier,
  metadata,
  syncWindow,
  all,
  failed,
}

/// Discriminator for events emitted from native code to Dart.
enum PigeonConversationsEventType {
  clientSynchronizationStatusUpdated,
  connectionStateChanged,
  conversationAdded,
  conversationUpdated,
  conversationDeleted,
  conversationSynchronizationUpdated,
  messageAdded,
  messageUpdated,
  messageDeleted,
  participantAdded,
  participantUpdated,
  participantDeleted,
  typingStarted,
  typingEnded,
  userUpdated,
  userSubscribed,
  userUnsubscribed,
  tokenAboutToExpire,
  tokenExpired,
  notificationSubscribed,
  error,
}

enum PigeonMessageContentType {
  text,
  media,
}

class PigeonConnectRequest {
  PigeonConnectRequest({
    required this.accessToken,
  });

  String accessToken;

  Object encode() {
    return <Object?>[
      accessToken,
    ];
  }

  static PigeonConnectRequest decode(Object result) {
    result as List<Object?>;
    return PigeonConnectRequest(
      accessToken: result[0]! as String,
    );
  }
}

class PigeonConversationDto {
  PigeonConversationDto({
    required this.sid,
    required this.uniqueName,
    required this.friendlyName,
    this.lastMessageIndex,
  });

  String sid;

  String uniqueName;

  String friendlyName;

  int? lastMessageIndex;

  Object encode() {
    return <Object?>[
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    ];
  }

  static PigeonConversationDto decode(Object result) {
    result as List<Object?>;
    return PigeonConversationDto(
      sid: result[0]! as String,
      uniqueName: result[1]! as String,
      friendlyName: result[2]! as String,
      lastMessageIndex: result[3] as int?,
    );
  }
}

class PigeonMediaAttachmentDto {
  PigeonMediaAttachmentDto({
    required this.sid,
    required this.contentType,
    required this.filename,
    required this.sizeBytes,
  });

  String sid;

  String contentType;

  String filename;

  int sizeBytes;

  Object encode() {
    return <Object?>[
      sid,
      contentType,
      filename,
      sizeBytes,
    ];
  }

  static PigeonMediaAttachmentDto decode(Object result) {
    result as List<Object?>;
    return PigeonMediaAttachmentDto(
      sid: result[0]! as String,
      contentType: result[1]! as String,
      filename: result[2]! as String,
      sizeBytes: result[3]! as int,
    );
  }
}

class PigeonMessageDto {
  PigeonMessageDto({
    required this.sid,
    required this.conversationSid,
    required this.author,
    required this.body,
    required this.messageIndex,
    required this.dateCreatedEpochMs,
    required this.contentType,
    this.mediaAttachments,
    this.attributesJson,
  });

  String sid;

  String conversationSid;

  String author;

  String body;

  int messageIndex;

  int dateCreatedEpochMs;

  PigeonMessageContentType contentType;

  List<PigeonMediaAttachmentDto?>? mediaAttachments;

  String? attributesJson;

  Object encode() {
    return <Object?>[
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType.index,
      mediaAttachments,
      attributesJson,
    ];
  }

  static PigeonMessageDto decode(Object result) {
    result as List<Object?>;
    return PigeonMessageDto(
      sid: result[0]! as String,
      conversationSid: result[1]! as String,
      author: result[2]! as String,
      body: result[3]! as String,
      messageIndex: result[4]! as int,
      dateCreatedEpochMs: result[5]! as int,
      contentType: PigeonMessageContentType.values[result[6]! as int],
      mediaAttachments: (result[7] as List<Object?>?)?.cast<PigeonMediaAttachmentDto?>(),
      attributesJson: result[8] as String?,
    );
  }
}

class PigeonParticipantDto {
  PigeonParticipantDto({
    required this.sid,
    required this.identity,
    required this.conversationSid,
  });

  String sid;

  String identity;

  String conversationSid;

  Object encode() {
    return <Object?>[
      sid,
      identity,
      conversationSid,
    ];
  }

  static PigeonParticipantDto decode(Object result) {
    result as List<Object?>;
    return PigeonParticipantDto(
      sid: result[0]! as String,
      identity: result[1]! as String,
      conversationSid: result[2]! as String,
    );
  }
}

class PigeonUserDto {
  PigeonUserDto({
    required this.identity,
    this.friendlyName,
  });

  String identity;

  String? friendlyName;

  Object encode() {
    return <Object?>[
      identity,
      friendlyName,
    ];
  }

  static PigeonUserDto decode(Object result) {
    result as List<Object?>;
    return PigeonUserDto(
      identity: result[0]! as String,
      friendlyName: result[1] as String?,
    );
  }
}

class PigeonSendMessageRequest {
  PigeonSendMessageRequest({
    required this.conversationSid,
    required this.body,
    this.attributesJson,
  });

  String conversationSid;

  String body;

  String? attributesJson;

  Object encode() {
    return <Object?>[
      conversationSid,
      body,
      attributesJson,
    ];
  }

  static PigeonSendMessageRequest decode(Object result) {
    result as List<Object?>;
    return PigeonSendMessageRequest(
      conversationSid: result[0]! as String,
      body: result[1]! as String,
      attributesJson: result[2] as String?,
    );
  }
}

class PigeonGetMessagesRequest {
  PigeonGetMessagesRequest({
    required this.conversationSid,
    required this.count,
  });

  String conversationSid;

  int count;

  Object encode() {
    return <Object?>[
      conversationSid,
      count,
    ];
  }

  static PigeonGetMessagesRequest decode(Object result) {
    result as List<Object?>;
    return PigeonGetMessagesRequest(
      conversationSid: result[0]! as String,
      count: result[1]! as int,
    );
  }
}

class PigeonGetMessagesBeforeRequest {
  PigeonGetMessagesBeforeRequest({
    required this.conversationSid,
    required this.beforeMessageIndex,
    required this.count,
  });

  String conversationSid;

  int beforeMessageIndex;

  int count;

  Object encode() {
    return <Object?>[
      conversationSid,
      beforeMessageIndex,
      count,
    ];
  }

  static PigeonGetMessagesBeforeRequest decode(Object result) {
    result as List<Object?>;
    return PigeonGetMessagesBeforeRequest(
      conversationSid: result[0]! as String,
      beforeMessageIndex: result[1]! as int,
      count: result[2]! as int,
    );
  }
}

class PigeonSendMediaMessageRequest {
  PigeonSendMediaMessageRequest({
    required this.conversationSid,
    required this.filePath,
    required this.mimeType,
    required this.filename,
    this.caption,
    this.attributesJson,
  });

  String conversationSid;

  String filePath;

  String mimeType;

  String filename;

  String? caption;

  String? attributesJson;

  Object encode() {
    return <Object?>[
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    ];
  }

  static PigeonSendMediaMessageRequest decode(Object result) {
    result as List<Object?>;
    return PigeonSendMediaMessageRequest(
      conversationSid: result[0]! as String,
      filePath: result[1]! as String,
      mimeType: result[2]! as String,
      filename: result[3]! as String,
      caption: result[4] as String?,
      attributesJson: result[5] as String?,
    );
  }
}

class PigeonGetMediaTemporaryUrlRequest {
  PigeonGetMediaTemporaryUrlRequest({
    required this.conversationSid,
    required this.messageIndex,
    required this.mediaSid,
  });

  String conversationSid;

  int messageIndex;

  String mediaSid;

  Object encode() {
    return <Object?>[
      conversationSid,
      messageIndex,
      mediaSid,
    ];
  }

  static PigeonGetMediaTemporaryUrlRequest decode(Object result) {
    result as List<Object?>;
    return PigeonGetMediaTemporaryUrlRequest(
      conversationSid: result[0]! as String,
      messageIndex: result[1]! as int,
      mediaSid: result[2]! as String,
    );
  }
}

class PigeonConversationRequest {
  PigeonConversationRequest({
    required this.conversationSid,
  });

  String conversationSid;

  Object encode() {
    return <Object?>[
      conversationSid,
    ];
  }

  static PigeonConversationRequest decode(Object result) {
    result as List<Object?>;
    return PigeonConversationRequest(
      conversationSid: result[0]! as String,
    );
  }
}

class PigeonConversationsNativeEvent {
  PigeonConversationsNativeEvent({
    required this.type,
    this.synchronizationStatus,
    this.connectionState,
    this.conversationSyncStatus,
    this.conversation,
    this.message,
    this.participant,
    this.user,
    this.updateReason,
    this.errorCode,
    this.errorMessage,
  });

  PigeonConversationsEventType type;

  PigeonClientSynchronizationStatus? synchronizationStatus;

  PigeonClientConnectionState? connectionState;

  PigeonConversationSynchronizationStatus? conversationSyncStatus;

  PigeonConversationDto? conversation;

  PigeonMessageDto? message;

  PigeonParticipantDto? participant;

  PigeonUserDto? user;

  String? updateReason;

  String? errorCode;

  String? errorMessage;

  Object encode() {
    return <Object?>[
      type.index,
      synchronizationStatus?.index,
      connectionState?.index,
      conversationSyncStatus?.index,
      conversation?.encode(),
      message?.encode(),
      participant?.encode(),
      user?.encode(),
      updateReason,
      errorCode,
      errorMessage,
    ];
  }

  static PigeonConversationsNativeEvent decode(Object result) {
    result as List<Object?>;
    return PigeonConversationsNativeEvent(
      type: PigeonConversationsEventType.values[result[0]! as int],
      synchronizationStatus: result[1] != null
          ? PigeonClientSynchronizationStatus.values[result[1]! as int]
          : null,
      connectionState: result[2] != null
          ? PigeonClientConnectionState.values[result[2]! as int]
          : null,
      conversationSyncStatus: result[3] != null
          ? PigeonConversationSynchronizationStatus.values[result[3]! as int]
          : null,
      conversation: result[4] != null
          ? PigeonConversationDto.decode(result[4]! as List<Object?>)
          : null,
      message: result[5] != null
          ? PigeonMessageDto.decode(result[5]! as List<Object?>)
          : null,
      participant: result[6] != null
          ? PigeonParticipantDto.decode(result[6]! as List<Object?>)
          : null,
      user: result[7] != null
          ? PigeonUserDto.decode(result[7]! as List<Object?>)
          : null,
      updateReason: result[8] as String?,
      errorCode: result[9] as String?,
      errorMessage: result[10] as String?,
    );
  }
}

class _TwilioConversationsHostApiCodec extends StandardMessageCodec {
  const _TwilioConversationsHostApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonConnectRequest) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonConversationDto) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PigeonConversationRequest) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PigeonGetMediaTemporaryUrlRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PigeonGetMessagesBeforeRequest) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PigeonGetMessagesRequest) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else if (value is PigeonMediaAttachmentDto) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else if (value is PigeonMessageDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    } else if (value is PigeonParticipantDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSendMediaMessageRequest) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    } else if (value is PigeonSendMessageRequest) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonConnectRequest.decode(readValue(buffer)!);
      case 129: 
        return PigeonConversationDto.decode(readValue(buffer)!);
      case 130: 
        return PigeonConversationRequest.decode(readValue(buffer)!);
      case 131: 
        return PigeonGetMediaTemporaryUrlRequest.decode(readValue(buffer)!);
      case 132: 
        return PigeonGetMessagesBeforeRequest.decode(readValue(buffer)!);
      case 133: 
        return PigeonGetMessagesRequest.decode(readValue(buffer)!);
      case 134: 
        return PigeonMediaAttachmentDto.decode(readValue(buffer)!);
      case 135: 
        return PigeonMessageDto.decode(readValue(buffer)!);
      case 136: 
        return PigeonParticipantDto.decode(readValue(buffer)!);
      case 137: 
        return PigeonSendMediaMessageRequest.decode(readValue(buffer)!);
      case 138: 
        return PigeonSendMessageRequest.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TwilioConversationsHostApi {
  /// Constructor for [TwilioConversationsHostApi].  The [binaryMessenger] named argument is
  /// available for dependency injection.  If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TwilioConversationsHostApi({BinaryMessenger? binaryMessenger})
      : _binaryMessenger = binaryMessenger;
  final BinaryMessenger? _binaryMessenger;

  static const MessageCodec<Object?> codec = _TwilioConversationsHostApiCodec();

  Future<void> connect(PigeonConnectRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> disconnect() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<void> updateAccessToken(String arg_accessToken) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_accessToken]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }

  Future<PigeonMessageDto> sendMessage(PigeonSendMessageRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PigeonMessageDto?)!;
    }
  }

  Future<List<PigeonConversationDto?>> listConversations() async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(null) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<PigeonConversationDto?>();
    }
  }

  Future<PigeonConversationDto> getConversation(String arg_sidOrUniqueName) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_sidOrUniqueName]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PigeonConversationDto?)!;
    }
  }

  Future<List<PigeonMessageDto?>> getLastMessages(PigeonGetMessagesRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<PigeonMessageDto?>();
    }
  }

  Future<List<PigeonMessageDto?>> getMessagesBefore(PigeonGetMessagesBeforeRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<PigeonMessageDto?>();
    }
  }

  Future<PigeonMessageDto> sendMediaMessage(PigeonSendMediaMessageRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as PigeonMessageDto?)!;
    }
  }

  Future<String> getMediaTemporaryUrl(PigeonGetMediaTemporaryUrlRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as String?)!;
    }
  }

  Future<List<PigeonParticipantDto?>> getParticipants(PigeonConversationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else if (replyList[0] == null) {
      throw PlatformException(
        code: 'null-error',
        message: 'Host platform returned null value for non-null return value.',
      );
    } else {
      return (replyList[0] as List<Object?>?)!.cast<PigeonParticipantDto?>();
    }
  }

  Future<void> sendTyping(PigeonConversationRequest arg_request) async {
    final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
        'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping', codec,
        binaryMessenger: _binaryMessenger);
    final List<Object?>? replyList =
        await channel.send(<Object?>[arg_request]) as List<Object?>?;
    if (replyList == null) {
      throw PlatformException(
        code: 'channel-error',
        message: 'Unable to establish connection on channel.',
      );
    } else if (replyList.length > 1) {
      throw PlatformException(
        code: replyList[0]! as String,
        message: replyList[1] as String?,
        details: replyList[2],
      );
    } else {
      return;
    }
  }
}

class _TwilioConversationsFlutterApiCodec extends StandardMessageCodec {
  const _TwilioConversationsFlutterApiCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is PigeonConversationDto) {
      buffer.putUint8(128);
      writeValue(buffer, value.encode());
    } else if (value is PigeonConversationsNativeEvent) {
      buffer.putUint8(129);
      writeValue(buffer, value.encode());
    } else if (value is PigeonMediaAttachmentDto) {
      buffer.putUint8(130);
      writeValue(buffer, value.encode());
    } else if (value is PigeonMessageDto) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    } else if (value is PigeonParticipantDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    } else if (value is PigeonUserDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 128: 
        return PigeonConversationDto.decode(readValue(buffer)!);
      case 129: 
        return PigeonConversationsNativeEvent.decode(readValue(buffer)!);
      case 130: 
        return PigeonMediaAttachmentDto.decode(readValue(buffer)!);
      case 131: 
        return PigeonMessageDto.decode(readValue(buffer)!);
      case 132: 
        return PigeonParticipantDto.decode(readValue(buffer)!);
      case 133: 
        return PigeonUserDto.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

abstract class TwilioConversationsFlutterApi {
  static const MessageCodec<Object?> codec = _TwilioConversationsFlutterApiCodec();

  void onNativeEvent(PigeonConversationsNativeEvent event);

  static void setup(TwilioConversationsFlutterApi? api, {BinaryMessenger? binaryMessenger}) {
    {
      final BasicMessageChannel<Object?> channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent', codec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        channel.setMessageHandler(null);
      } else {
        channel.setMessageHandler((Object? message) async {
          assert(message != null,
          'Argument for dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent was null.');
          final List<Object?> args = (message as List<Object?>?)!;
          final PigeonConversationsNativeEvent? arg_event = (args[0] as PigeonConversationsNativeEvent?);
          assert(arg_event != null,
              'Argument for dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent was null, expected non-null PigeonConversationsNativeEvent.');
          api.onNativeEvent(arg_event!);
          return;
        });
      }
    }
  }
}
