// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


/// Client synchronization status mirrored from the Twilio Conversations SDK.
enum ClientSynchronizationStatus {
  unknown,
  started,
  conversationsListCompleted,
  completed,
  failed;
}

/// Native client connection state.
enum ClientConnectionState {
  unknown,
  connecting,
  connected,
  disconnected,
  denied,
  error,
  fatal;
}

/// Per-conversation synchronization state.
enum ConversationSynchronizationStatus {
  unknown,
  none,
  identifier,
  metadata,
  syncWindow,
  all,
  failed;
}

/// Discriminator for events emitted from native code to Dart.
enum ConversationsEventType {
  clientSynchronizationStatusUpdated,
  connectionStateChanged,
  conversationAdded,
  conversationUpdated,
  conversationDeleted,
  conversationSynchronizationUpdated,
  messageAdded,
  messageUpdated,
  messageDeleted,
  participantAdded,
  participantUpdated,
  participantDeleted,
  typingStarted,
  typingEnded,
  userUpdated,
  userSubscribed,
  userUnsubscribed,
  tokenAboutToExpire,
  tokenExpired,
  notificationSubscribed,
  error;
}

enum MessageContentType {
  text,
  media;
}

class ConnectRequest {
  ConnectRequest({
    required this.accessToken,
  });

  String accessToken;

  List<Object?> _toList() {
    return <Object?>[
      accessToken,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConnectRequest decode(Object result) {
    result as List<Object?>;
    return ConnectRequest(
      accessToken: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConnectRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessToken, other.accessToken);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConnectRequest(accessToken: $accessToken)';
  }
}

class ConversationDto {
  ConversationDto({
    required this.sid,
    required this.uniqueName,
    required this.friendlyName,
    this.lastMessageIndex,
  });

  String sid;

  String uniqueName;

  String friendlyName;

  int? lastMessageIndex;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConversationDto decode(Object result) {
    result as List<Object?>;
    return ConversationDto(
      sid: result[0]! as String,
      uniqueName: result[1]! as String,
      friendlyName: result[2]! as String,
      lastMessageIndex: result[3] as int?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConversationDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(uniqueName, other.uniqueName) && _deepEquals(friendlyName, other.friendlyName) && _deepEquals(lastMessageIndex, other.lastMessageIndex);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConversationDto(sid: $sid, uniqueName: $uniqueName, friendlyName: $friendlyName, lastMessageIndex: $lastMessageIndex)';
  }
}

class MediaAttachmentDto {
  MediaAttachmentDto({
    required this.sid,
    required this.contentType,
    required this.filename,
    required this.sizeBytes,
  });

  String sid;

  String contentType;

  String filename;

  int sizeBytes;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      contentType,
      filename,
      sizeBytes,
    ];
  }

  Object encode() {
    return _toList();  }

  static MediaAttachmentDto decode(Object result) {
    result as List<Object?>;
    return MediaAttachmentDto(
      sid: result[0]! as String,
      contentType: result[1]! as String,
      filename: result[2]! as String,
      sizeBytes: result[3]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MediaAttachmentDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(contentType, other.contentType) && _deepEquals(filename, other.filename) && _deepEquals(sizeBytes, other.sizeBytes);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MediaAttachmentDto(sid: $sid, contentType: $contentType, filename: $filename, sizeBytes: $sizeBytes)';
  }
}

class MessageDto {
  MessageDto({
    required this.sid,
    required this.conversationSid,
    required this.author,
    required this.body,
    required this.messageIndex,
    required this.dateCreatedEpochMs,
    this.contentType = MessageContentType.text,
    this.mediaAttachments,
    this.attributesJson,
  });

  String sid;

  String conversationSid;

  String author;

  String body;

  int messageIndex;

  int dateCreatedEpochMs;

  MessageContentType contentType;

  List<MediaAttachmentDto?>? mediaAttachments;

  String? attributesJson;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType,
      mediaAttachments,
      attributesJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static MessageDto decode(Object result) {
    result as List<Object?>;
    return MessageDto(
      sid: result[0]! as String,
      conversationSid: result[1]! as String,
      author: result[2]! as String,
      body: result[3]! as String,
      messageIndex: result[4]! as int,
      dateCreatedEpochMs: result[5]! as int,
      contentType: result[6]! as MessageContentType,
      mediaAttachments: (result[7] as List<Object?>?)?.cast<MediaAttachmentDto?>(),
      attributesJson: result[8] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! MessageDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(conversationSid, other.conversationSid) && _deepEquals(author, other.author) && _deepEquals(body, other.body) && _deepEquals(messageIndex, other.messageIndex) && _deepEquals(dateCreatedEpochMs, other.dateCreatedEpochMs) && _deepEquals(contentType, other.contentType) && _deepEquals(mediaAttachments, other.mediaAttachments) && _deepEquals(attributesJson, other.attributesJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'MessageDto(sid: $sid, conversationSid: $conversationSid, author: $author, body: $body, messageIndex: $messageIndex, dateCreatedEpochMs: $dateCreatedEpochMs, contentType: $contentType, mediaAttachments: $mediaAttachments, attributesJson: $attributesJson)';
  }
}

class ParticipantDto {
  ParticipantDto({
    required this.sid,
    required this.identity,
    required this.conversationSid,
  });

  String sid;

  String identity;

  String conversationSid;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      identity,
      conversationSid,
    ];
  }

  Object encode() {
    return _toList();  }

  static ParticipantDto decode(Object result) {
    result as List<Object?>;
    return ParticipantDto(
      sid: result[0]! as String,
      identity: result[1]! as String,
      conversationSid: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ParticipantDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(identity, other.identity) && _deepEquals(conversationSid, other.conversationSid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ParticipantDto(sid: $sid, identity: $identity, conversationSid: $conversationSid)';
  }
}

class UserDto {
  UserDto({
    required this.identity,
    this.friendlyName,
  });

  String identity;

  String? friendlyName;

  List<Object?> _toList() {
    return <Object?>[
      identity,
      friendlyName,
    ];
  }

  Object encode() {
    return _toList();  }

  static UserDto decode(Object result) {
    result as List<Object?>;
    return UserDto(
      identity: result[0]! as String,
      friendlyName: result[1] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! UserDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(identity, other.identity) && _deepEquals(friendlyName, other.friendlyName);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'UserDto(identity: $identity, friendlyName: $friendlyName)';
  }
}

class SendMessageRequest {
  SendMessageRequest({
    required this.conversationSid,
    required this.body,
    this.attributesJson,
  });

  String conversationSid;

  String body;

  String? attributesJson;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
      body,
      attributesJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static SendMessageRequest decode(Object result) {
    result as List<Object?>;
    return SendMessageRequest(
      conversationSid: result[0]! as String,
      body: result[1]! as String,
      attributesJson: result[2] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SendMessageRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid) && _deepEquals(body, other.body) && _deepEquals(attributesJson, other.attributesJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SendMessageRequest(conversationSid: $conversationSid, body: $body, attributesJson: $attributesJson)';
  }
}

class GetMessagesRequest {
  GetMessagesRequest({
    required this.conversationSid,
    required this.count,
  });

  String conversationSid;

  int count;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
      count,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetMessagesRequest decode(Object result) {
    result as List<Object?>;
    return GetMessagesRequest(
      conversationSid: result[0]! as String,
      count: result[1]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetMessagesRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid) && _deepEquals(count, other.count);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GetMessagesRequest(conversationSid: $conversationSid, count: $count)';
  }
}

class GetMessagesBeforeRequest {
  GetMessagesBeforeRequest({
    required this.conversationSid,
    required this.beforeMessageIndex,
    required this.count,
  });

  String conversationSid;

  int beforeMessageIndex;

  int count;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
      beforeMessageIndex,
      count,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetMessagesBeforeRequest decode(Object result) {
    result as List<Object?>;
    return GetMessagesBeforeRequest(
      conversationSid: result[0]! as String,
      beforeMessageIndex: result[1]! as int,
      count: result[2]! as int,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetMessagesBeforeRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid) && _deepEquals(beforeMessageIndex, other.beforeMessageIndex) && _deepEquals(count, other.count);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GetMessagesBeforeRequest(conversationSid: $conversationSid, beforeMessageIndex: $beforeMessageIndex, count: $count)';
  }
}

class SendMediaMessageRequest {
  SendMediaMessageRequest({
    required this.conversationSid,
    required this.filePath,
    required this.mimeType,
    required this.filename,
    this.caption,
    this.attributesJson,
  });

  String conversationSid;

  String filePath;

  String mimeType;

  String filename;

  String? caption;

  String? attributesJson;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    ];
  }

  Object encode() {
    return _toList();  }

  static SendMediaMessageRequest decode(Object result) {
    result as List<Object?>;
    return SendMediaMessageRequest(
      conversationSid: result[0]! as String,
      filePath: result[1]! as String,
      mimeType: result[2]! as String,
      filename: result[3]! as String,
      caption: result[4] as String?,
      attributesJson: result[5] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! SendMediaMessageRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid) && _deepEquals(filePath, other.filePath) && _deepEquals(mimeType, other.mimeType) && _deepEquals(filename, other.filename) && _deepEquals(caption, other.caption) && _deepEquals(attributesJson, other.attributesJson);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'SendMediaMessageRequest(conversationSid: $conversationSid, filePath: $filePath, mimeType: $mimeType, filename: $filename, caption: $caption, attributesJson: $attributesJson)';
  }
}

class GetMediaTemporaryUrlRequest {
  GetMediaTemporaryUrlRequest({
    required this.conversationSid,
    required this.messageIndex,
    required this.mediaSid,
  });

  String conversationSid;

  int messageIndex;

  String mediaSid;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
      messageIndex,
      mediaSid,
    ];
  }

  Object encode() {
    return _toList();  }

  static GetMediaTemporaryUrlRequest decode(Object result) {
    result as List<Object?>;
    return GetMediaTemporaryUrlRequest(
      conversationSid: result[0]! as String,
      messageIndex: result[1]! as int,
      mediaSid: result[2]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! GetMediaTemporaryUrlRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid) && _deepEquals(messageIndex, other.messageIndex) && _deepEquals(mediaSid, other.mediaSid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'GetMediaTemporaryUrlRequest(conversationSid: $conversationSid, messageIndex: $messageIndex, mediaSid: $mediaSid)';
  }
}

class ConversationRequest {
  ConversationRequest({
    required this.conversationSid,
  });

  String conversationSid;

  List<Object?> _toList() {
    return <Object?>[
      conversationSid,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConversationRequest decode(Object result) {
    result as List<Object?>;
    return ConversationRequest(
      conversationSid: result[0]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConversationRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(conversationSid, other.conversationSid);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConversationRequest(conversationSid: $conversationSid)';
  }
}

class ConversationsNativeEvent {
  ConversationsNativeEvent({
    required this.type,
    this.synchronizationStatus,
    this.connectionState,
    this.conversationSyncStatus,
    this.conversation,
    this.message,
    this.participant,
    this.user,
    this.updateReason,
    this.errorCode,
    this.errorMessage,
  });

  ConversationsEventType type;

  ClientSynchronizationStatus? synchronizationStatus;

  ClientConnectionState? connectionState;

  ConversationSynchronizationStatus? conversationSyncStatus;

  ConversationDto? conversation;

  MessageDto? message;

  ParticipantDto? participant;

  UserDto? user;

  String? updateReason;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      type,
      synchronizationStatus,
      connectionState,
      conversationSyncStatus,
      conversation,
      message,
      participant,
      user,
      updateReason,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static ConversationsNativeEvent decode(Object result) {
    result as List<Object?>;
    return ConversationsNativeEvent(
      type: result[0]! as ConversationsEventType,
      synchronizationStatus: result[1] as ClientSynchronizationStatus?,
      connectionState: result[2] as ClientConnectionState?,
      conversationSyncStatus: result[3] as ConversationSynchronizationStatus?,
      conversation: result[4] as ConversationDto?,
      message: result[5] as MessageDto?,
      participant: result[6] as ParticipantDto?,
      user: result[7] as UserDto?,
      updateReason: result[8] as String?,
      errorCode: result[9] as String?,
      errorMessage: result[10] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! ConversationsNativeEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(synchronizationStatus, other.synchronizationStatus) && _deepEquals(connectionState, other.connectionState) && _deepEquals(conversationSyncStatus, other.conversationSyncStatus) && _deepEquals(conversation, other.conversation) && _deepEquals(message, other.message) && _deepEquals(participant, other.participant) && _deepEquals(user, other.user) && _deepEquals(updateReason, other.updateReason) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'ConversationsNativeEvent(type: $type, synchronizationStatus: $synchronizationStatus, connectionState: $connectionState, conversationSyncStatus: $conversationSyncStatus, conversation: $conversation, message: $message, participant: $participant, user: $user, updateReason: $updateReason, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is ClientSynchronizationStatus) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is ClientConnectionState) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is ConversationSynchronizationStatus) {
      buffer.putUint8(131);
      writeValue(buffer, value.index);
    }    else if (value is ConversationsEventType) {
      buffer.putUint8(132);
      writeValue(buffer, value.index);
    }    else if (value is MessageContentType) {
      buffer.putUint8(133);
      writeValue(buffer, value.index);
    }    else if (value is ConnectRequest) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    }    else if (value is ConversationDto) {
      buffer.putUint8(135);
      writeValue(buffer, value.encode());
    }    else if (value is MediaAttachmentDto) {
      buffer.putUint8(136);
      writeValue(buffer, value.encode());
    }    else if (value is MessageDto) {
      buffer.putUint8(137);
      writeValue(buffer, value.encode());
    }    else if (value is ParticipantDto) {
      buffer.putUint8(138);
      writeValue(buffer, value.encode());
    }    else if (value is UserDto) {
      buffer.putUint8(139);
      writeValue(buffer, value.encode());
    }    else if (value is SendMessageRequest) {
      buffer.putUint8(140);
      writeValue(buffer, value.encode());
    }    else if (value is GetMessagesRequest) {
      buffer.putUint8(141);
      writeValue(buffer, value.encode());
    }    else if (value is GetMessagesBeforeRequest) {
      buffer.putUint8(142);
      writeValue(buffer, value.encode());
    }    else if (value is SendMediaMessageRequest) {
      buffer.putUint8(143);
      writeValue(buffer, value.encode());
    }    else if (value is GetMediaTemporaryUrlRequest) {
      buffer.putUint8(144);
      writeValue(buffer, value.encode());
    }    else if (value is ConversationRequest) {
      buffer.putUint8(145);
      writeValue(buffer, value.encode());
    }    else if (value is ConversationsNativeEvent) {
      buffer.putUint8(146);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : ClientSynchronizationStatus.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : ClientConnectionState.values[value];
      case 131:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConversationSynchronizationStatus.values[value];
      case 132:
        final value = readValue(buffer) as int?;
        return value == null ? null : ConversationsEventType.values[value];
      case 133:
        final value = readValue(buffer) as int?;
        return value == null ? null : MessageContentType.values[value];
      case 134:
        return ConnectRequest.decode(readValue(buffer)!);
      case 135:
        return ConversationDto.decode(readValue(buffer)!);
      case 136:
        return MediaAttachmentDto.decode(readValue(buffer)!);
      case 137:
        return MessageDto.decode(readValue(buffer)!);
      case 138:
        return ParticipantDto.decode(readValue(buffer)!);
      case 139:
        return UserDto.decode(readValue(buffer)!);
      case 140:
        return SendMessageRequest.decode(readValue(buffer)!);
      case 141:
        return GetMessagesRequest.decode(readValue(buffer)!);
      case 142:
        return GetMessagesBeforeRequest.decode(readValue(buffer)!);
      case 143:
        return SendMediaMessageRequest.decode(readValue(buffer)!);
      case 144:
        return GetMediaTemporaryUrlRequest.decode(readValue(buffer)!);
      case 145:
        return ConversationRequest.decode(readValue(buffer)!);
      case 146:
        return ConversationsNativeEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TwilioConversationsHostApi {
  /// Constructor for [TwilioConversationsHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TwilioConversationsHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<void> connect(ConnectRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> updateAccessToken(String accessToken) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[accessToken]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<MessageDto> sendMessage(SendMessageRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MessageDto;
  }

  Future<List<ConversationDto>> listConversations() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ConversationDto>();
  }

  Future<ConversationDto> getConversation(String sidOrUniqueName) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[sidOrUniqueName]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as ConversationDto;
  }

  Future<List<MessageDto>> getLastMessages(GetMessagesRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<MessageDto>();
  }

  Future<List<MessageDto>> getMessagesBefore(GetMessagesBeforeRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<MessageDto>();
  }

  Future<MessageDto> sendMediaMessage(SendMediaMessageRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as MessageDto;
  }

  Future<String> getMediaTemporaryUrl(GetMediaTemporaryUrlRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return pigeonVar_replyValue! as String;
  }

  Future<List<ParticipantDto>> getParticipants(ConversationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    final Object? pigeonVar_replyValue = _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: false,
    )
    ;
    return (pigeonVar_replyValue! as List<Object?>).cast<ParticipantDto>();
  }

  Future<void> sendTyping(ConversationRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class TwilioConversationsFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNativeEvent(ConversationsNativeEvent event);

  static void setUp(TwilioConversationsFlutterApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final ConversationsNativeEvent arg_event = args[0]! as ConversationsNativeEvent;
          try {
            api.onNativeEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
