// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v11.0.1), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation
#if os(iOS)
import Flutter
#elseif os(macOS)
import FlutterMacOS
#else
#error("Unsupported platform.")
#endif

private func isNullish(_ value: Any?) -> Bool {
  return value is NSNull || value == nil
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details
    ]
  }
  return [
    "\(error)",
    "\(type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)"
  ]
}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}

/// Client synchronization status mirrored from the Twilio Conversations SDK.
enum PigeonClientSynchronizationStatus: Int {
  case unknown = 0
  case started = 1
  case conversationsListCompleted = 2
  case completed = 3
  case failed = 4
}

/// Native client connection state.
enum PigeonClientConnectionState: Int {
  case unknown = 0
  case connecting = 1
  case connected = 2
  case disconnected = 3
  case denied = 4
  case error = 5
  case fatal = 6
}

/// Per-conversation synchronization state.
enum PigeonConversationSynchronizationStatus: Int {
  case unknown = 0
  case none = 1
  case identifier = 2
  case metadata = 3
  case syncWindow = 4
  case all = 5
  case failed = 6
}

/// Discriminator for events emitted from native code to Dart.
enum PigeonConversationsEventType: Int {
  case clientSynchronizationStatusUpdated = 0
  case connectionStateChanged = 1
  case conversationAdded = 2
  case conversationUpdated = 3
  case conversationDeleted = 4
  case conversationSynchronizationUpdated = 5
  case messageAdded = 6
  case messageUpdated = 7
  case messageDeleted = 8
  case participantAdded = 9
  case participantUpdated = 10
  case participantDeleted = 11
  case typingStarted = 12
  case typingEnded = 13
  case userUpdated = 14
  case userSubscribed = 15
  case userUnsubscribed = 16
  case tokenAboutToExpire = 17
  case tokenExpired = 18
  case notificationSubscribed = 19
  case error = 20
}

enum PigeonMessageContentType: Int {
  case text = 0
  case media = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonConnectRequest {
  var accessToken: String

  static func fromList(_ list: [Any?]) -> PigeonConnectRequest? {
    let accessToken = list[0] as! String

    return PigeonConnectRequest(
      accessToken: accessToken
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonConversationDto {
  var sid: String
  var uniqueName: String
  var friendlyName: String
  var lastMessageIndex: Int64? = nil

  static func fromList(_ list: [Any?]) -> PigeonConversationDto? {
    let sid = list[0] as! String
    let uniqueName = list[1] as! String
    let friendlyName = list[2] as! String
    let lastMessageIndex: Int64? = isNullish(list[3]) ? nil : (list[3] is Int64? ? list[3] as! Int64? : Int64(list[3] as! Int32))

    return PigeonConversationDto(
      sid: sid,
      uniqueName: uniqueName,
      friendlyName: friendlyName,
      lastMessageIndex: lastMessageIndex
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonMediaAttachmentDto {
  var sid: String
  var contentType: String
  var filename: String
  var sizeBytes: Int64

  static func fromList(_ list: [Any?]) -> PigeonMediaAttachmentDto? {
    let sid = list[0] as! String
    let contentType = list[1] as! String
    let filename = list[2] as! String
    let sizeBytes = list[3] is Int64 ? list[3] as! Int64 : Int64(list[3] as! Int32)

    return PigeonMediaAttachmentDto(
      sid: sid,
      contentType: contentType,
      filename: filename,
      sizeBytes: sizeBytes
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      contentType,
      filename,
      sizeBytes,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonMessageDto {
  var sid: String
  var conversationSid: String
  var author: String
  var body: String
  var messageIndex: Int64
  var dateCreatedEpochMs: Int64
  var contentType: PigeonMessageContentType
  var mediaAttachments: [PigeonMediaAttachmentDto?]? = nil
  var attributesJson: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonMessageDto? {
    let sid = list[0] as! String
    let conversationSid = list[1] as! String
    let author = list[2] as! String
    let body = list[3] as! String
    let messageIndex = list[4] is Int64 ? list[4] as! Int64 : Int64(list[4] as! Int32)
    let dateCreatedEpochMs = list[5] is Int64 ? list[5] as! Int64 : Int64(list[5] as! Int32)
    let contentType = PigeonMessageContentType(rawValue: list[6] as! Int)!
    let mediaAttachments: [PigeonMediaAttachmentDto?]? = nilOrValue(list[7])
    let attributesJson: String? = nilOrValue(list[8])

    return PigeonMessageDto(
      sid: sid,
      conversationSid: conversationSid,
      author: author,
      body: body,
      messageIndex: messageIndex,
      dateCreatedEpochMs: dateCreatedEpochMs,
      contentType: contentType,
      mediaAttachments: mediaAttachments,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType.rawValue,
      mediaAttachments,
      attributesJson,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonParticipantDto {
  var sid: String
  var identity: String
  var conversationSid: String

  static func fromList(_ list: [Any?]) -> PigeonParticipantDto? {
    let sid = list[0] as! String
    let identity = list[1] as! String
    let conversationSid = list[2] as! String

    return PigeonParticipantDto(
      sid: sid,
      identity: identity,
      conversationSid: conversationSid
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      identity,
      conversationSid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonUserDto {
  var identity: String
  var friendlyName: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonUserDto? {
    let identity = list[0] as! String
    let friendlyName: String? = nilOrValue(list[1])

    return PigeonUserDto(
      identity: identity,
      friendlyName: friendlyName
    )
  }
  func toList() -> [Any?] {
    return [
      identity,
      friendlyName,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonSendMessageRequest {
  var conversationSid: String
  var body: String
  var attributesJson: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonSendMessageRequest? {
    let conversationSid = list[0] as! String
    let body = list[1] as! String
    let attributesJson: String? = nilOrValue(list[2])

    return PigeonSendMessageRequest(
      conversationSid: conversationSid,
      body: body,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      body,
      attributesJson,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonGetMessagesRequest {
  var conversationSid: String
  var count: Int64

  static func fromList(_ list: [Any?]) -> PigeonGetMessagesRequest? {
    let conversationSid = list[0] as! String
    let count = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)

    return PigeonGetMessagesRequest(
      conversationSid: conversationSid,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      count,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonGetMessagesBeforeRequest {
  var conversationSid: String
  var beforeMessageIndex: Int64
  var count: Int64

  static func fromList(_ list: [Any?]) -> PigeonGetMessagesBeforeRequest? {
    let conversationSid = list[0] as! String
    let beforeMessageIndex = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let count = list[2] is Int64 ? list[2] as! Int64 : Int64(list[2] as! Int32)

    return PigeonGetMessagesBeforeRequest(
      conversationSid: conversationSid,
      beforeMessageIndex: beforeMessageIndex,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      beforeMessageIndex,
      count,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonSendMediaMessageRequest {
  var conversationSid: String
  var filePath: String
  var mimeType: String
  var filename: String
  var caption: String? = nil
  var attributesJson: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonSendMediaMessageRequest? {
    let conversationSid = list[0] as! String
    let filePath = list[1] as! String
    let mimeType = list[2] as! String
    let filename = list[3] as! String
    let caption: String? = nilOrValue(list[4])
    let attributesJson: String? = nilOrValue(list[5])

    return PigeonSendMediaMessageRequest(
      conversationSid: conversationSid,
      filePath: filePath,
      mimeType: mimeType,
      filename: filename,
      caption: caption,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonGetMediaTemporaryUrlRequest {
  var conversationSid: String
  var messageIndex: Int64
  var mediaSid: String

  static func fromList(_ list: [Any?]) -> PigeonGetMediaTemporaryUrlRequest? {
    let conversationSid = list[0] as! String
    let messageIndex = list[1] is Int64 ? list[1] as! Int64 : Int64(list[1] as! Int32)
    let mediaSid = list[2] as! String

    return PigeonGetMediaTemporaryUrlRequest(
      conversationSid: conversationSid,
      messageIndex: messageIndex,
      mediaSid: mediaSid
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      messageIndex,
      mediaSid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonConversationRequest {
  var conversationSid: String

  static func fromList(_ list: [Any?]) -> PigeonConversationRequest? {
    let conversationSid = list[0] as! String

    return PigeonConversationRequest(
      conversationSid: conversationSid
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
    ]
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct PigeonConversationsNativeEvent {
  var type: PigeonConversationsEventType
  var synchronizationStatus: PigeonClientSynchronizationStatus? = nil
  var connectionState: PigeonClientConnectionState? = nil
  var conversationSyncStatus: PigeonConversationSynchronizationStatus? = nil
  var conversation: PigeonConversationDto? = nil
  var message: PigeonMessageDto? = nil
  var participant: PigeonParticipantDto? = nil
  var user: PigeonUserDto? = nil
  var updateReason: String? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil

  static func fromList(_ list: [Any?]) -> PigeonConversationsNativeEvent? {
    let type = PigeonConversationsEventType(rawValue: list[0] as! Int)!
    var synchronizationStatus: PigeonClientSynchronizationStatus? = nil
    let synchronizationStatusEnumVal: Int? = nilOrValue(list[1])
    if let synchronizationStatusRawValue = synchronizationStatusEnumVal {
      synchronizationStatus = PigeonClientSynchronizationStatus(rawValue: synchronizationStatusRawValue)!
    }
    var connectionState: PigeonClientConnectionState? = nil
    let connectionStateEnumVal: Int? = nilOrValue(list[2])
    if let connectionStateRawValue = connectionStateEnumVal {
      connectionState = PigeonClientConnectionState(rawValue: connectionStateRawValue)!
    }
    var conversationSyncStatus: PigeonConversationSynchronizationStatus? = nil
    let conversationSyncStatusEnumVal: Int? = nilOrValue(list[3])
    if let conversationSyncStatusRawValue = conversationSyncStatusEnumVal {
      conversationSyncStatus = PigeonConversationSynchronizationStatus(rawValue: conversationSyncStatusRawValue)!
    }
    var conversation: PigeonConversationDto? = nil
    if let conversationList: [Any?] = nilOrValue(list[4]) {
      conversation = PigeonConversationDto.fromList(conversationList)
    }
    var message: PigeonMessageDto? = nil
    if let messageList: [Any?] = nilOrValue(list[5]) {
      message = PigeonMessageDto.fromList(messageList)
    }
    var participant: PigeonParticipantDto? = nil
    if let participantList: [Any?] = nilOrValue(list[6]) {
      participant = PigeonParticipantDto.fromList(participantList)
    }
    var user: PigeonUserDto? = nil
    if let userList: [Any?] = nilOrValue(list[7]) {
      user = PigeonUserDto.fromList(userList)
    }
    let updateReason: String? = nilOrValue(list[8])
    let errorCode: String? = nilOrValue(list[9])
    let errorMessage: String? = nilOrValue(list[10])

    return PigeonConversationsNativeEvent(
      type: type,
      synchronizationStatus: synchronizationStatus,
      connectionState: connectionState,
      conversationSyncStatus: conversationSyncStatus,
      conversation: conversation,
      message: message,
      participant: participant,
      user: user,
      updateReason: updateReason,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type.rawValue,
      synchronizationStatus?.rawValue,
      connectionState?.rawValue,
      conversationSyncStatus?.rawValue,
      conversation?.toList(),
      message?.toList(),
      participant?.toList(),
      user?.toList(),
      updateReason,
      errorCode,
      errorMessage,
    ]
  }
}

private class TwilioConversationsHostApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return PigeonConnectRequest.fromList(self.readValue() as! [Any?])
      case 129:
        return PigeonConversationDto.fromList(self.readValue() as! [Any?])
      case 130:
        return PigeonConversationRequest.fromList(self.readValue() as! [Any?])
      case 131:
        return PigeonGetMediaTemporaryUrlRequest.fromList(self.readValue() as! [Any?])
      case 132:
        return PigeonGetMessagesBeforeRequest.fromList(self.readValue() as! [Any?])
      case 133:
        return PigeonGetMessagesRequest.fromList(self.readValue() as! [Any?])
      case 134:
        return PigeonMediaAttachmentDto.fromList(self.readValue() as! [Any?])
      case 135:
        return PigeonMessageDto.fromList(self.readValue() as! [Any?])
      case 136:
        return PigeonParticipantDto.fromList(self.readValue() as! [Any?])
      case 137:
        return PigeonSendMediaMessageRequest.fromList(self.readValue() as! [Any?])
      case 138:
        return PigeonSendMessageRequest.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class TwilioConversationsHostApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonConnectRequest {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonConversationDto {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonConversationRequest {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonGetMediaTemporaryUrlRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonGetMessagesBeforeRequest {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonGetMessagesRequest {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonMediaAttachmentDto {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonMessageDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonParticipantDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonSendMediaMessageRequest {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonSendMessageRequest {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TwilioConversationsHostApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TwilioConversationsHostApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TwilioConversationsHostApiCodecWriter(data: data)
  }
}

class TwilioConversationsHostApiCodec: FlutterStandardMessageCodec {
  static let shared = TwilioConversationsHostApiCodec(readerWriter: TwilioConversationsHostApiCodecReaderWriter())
}

/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TwilioConversationsHostApi {
  func connect(request: PigeonConnectRequest, completion: @escaping (Result<Void, Error>) -> Void)
  func disconnect(completion: @escaping (Result<Void, Error>) -> Void)
  func updateAccessToken(accessToken: String, completion: @escaping (Result<Void, Error>) -> Void)
  func sendMessage(request: PigeonSendMessageRequest, completion: @escaping (Result<PigeonMessageDto, Error>) -> Void)
  func listConversations(completion: @escaping (Result<[PigeonConversationDto], Error>) -> Void)
  func getConversation(sidOrUniqueName: String, completion: @escaping (Result<PigeonConversationDto, Error>) -> Void)
  func getLastMessages(request: PigeonGetMessagesRequest, completion: @escaping (Result<[PigeonMessageDto], Error>) -> Void)
  func getMessagesBefore(request: PigeonGetMessagesBeforeRequest, completion: @escaping (Result<[PigeonMessageDto], Error>) -> Void)
  func sendMediaMessage(request: PigeonSendMediaMessageRequest, completion: @escaping (Result<PigeonMessageDto, Error>) -> Void)
  func getMediaTemporaryUrl(request: PigeonGetMediaTemporaryUrlRequest, completion: @escaping (Result<String, Error>) -> Void)
  func getParticipants(request: PigeonConversationRequest, completion: @escaping (Result<[PigeonParticipantDto], Error>) -> Void)
  func sendTyping(request: PigeonConversationRequest, completion: @escaping (Result<Void, Error>) -> Void)
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TwilioConversationsHostApiSetup {
  /// The codec used by TwilioConversationsHostApi.
  static var codec: FlutterStandardMessageCodec { TwilioConversationsHostApiCodec.shared }
  /// Sets up an instance of `TwilioConversationsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TwilioConversationsHostApi?) {
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonConnectRequest
        api.connect(request: requestArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        api.disconnect() { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let updateAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessTokenArg = args[0] as! String
        api.updateAccessToken(accessToken: accessTokenArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      updateAccessTokenChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonSendMessageRequest
        api.sendMessage(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let listConversationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listConversationsChannel.setMessageHandler { _, reply in
        api.listConversations() { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      listConversationsChannel.setMessageHandler(nil)
    }
    let getConversationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConversationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sidOrUniqueNameArg = args[0] as! String
        api.getConversation(sidOrUniqueName: sidOrUniqueNameArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getConversationChannel.setMessageHandler(nil)
    }
    let getLastMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLastMessagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonGetMessagesRequest
        api.getLastMessages(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getLastMessagesChannel.setMessageHandler(nil)
    }
    let getMessagesBeforeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMessagesBeforeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonGetMessagesBeforeRequest
        api.getMessagesBefore(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getMessagesBeforeChannel.setMessageHandler(nil)
    }
    let sendMediaMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMediaMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonSendMediaMessageRequest
        api.sendMediaMessage(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendMediaMessageChannel.setMessageHandler(nil)
    }
    let getMediaTemporaryUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaTemporaryUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonGetMediaTemporaryUrlRequest
        api.getMediaTemporaryUrl(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaTemporaryUrlChannel.setMessageHandler(nil)
    }
    let getParticipantsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getParticipantsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonConversationRequest
        api.getParticipants(request: requestArg) { result in
          switch result {
            case .success(let res):
              reply(wrapResult(res))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      getParticipantsChannel.setMessageHandler(nil)
    }
    let sendTypingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTypingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! PigeonConversationRequest
        api.sendTyping(request: requestArg) { result in
          switch result {
            case .success:
              reply(wrapResult(nil))
            case .failure(let error):
              reply(wrapError(error))
          }
        }
      }
    } else {
      sendTypingChannel.setMessageHandler(nil)
    }
  }
}
private class TwilioConversationsFlutterApiCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
      case 128:
        return PigeonConversationDto.fromList(self.readValue() as! [Any?])
      case 129:
        return PigeonConversationsNativeEvent.fromList(self.readValue() as! [Any?])
      case 130:
        return PigeonMediaAttachmentDto.fromList(self.readValue() as! [Any?])
      case 131:
        return PigeonMessageDto.fromList(self.readValue() as! [Any?])
      case 132:
        return PigeonParticipantDto.fromList(self.readValue() as! [Any?])
      case 133:
        return PigeonUserDto.fromList(self.readValue() as! [Any?])
      default:
        return super.readValue(ofType: type)
    }
  }
}

private class TwilioConversationsFlutterApiCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? PigeonConversationDto {
      super.writeByte(128)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonConversationsNativeEvent {
      super.writeByte(129)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonMediaAttachmentDto {
      super.writeByte(130)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonMessageDto {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonParticipantDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? PigeonUserDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class TwilioConversationsFlutterApiCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return TwilioConversationsFlutterApiCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return TwilioConversationsFlutterApiCodecWriter(data: data)
  }
}

class TwilioConversationsFlutterApiCodec: FlutterStandardMessageCodec {
  static let shared = TwilioConversationsFlutterApiCodec(readerWriter: TwilioConversationsFlutterApiCodecReaderWriter())
}

/// Generated class from Pigeon that represents Flutter messages that can be called from Swift.
class TwilioConversationsFlutterApi {
  private let binaryMessenger: FlutterBinaryMessenger
  init(binaryMessenger: FlutterBinaryMessenger){
    self.binaryMessenger = binaryMessenger
  }
  var codec: FlutterStandardMessageCodec {
    return TwilioConversationsFlutterApiCodec.shared
  }
  func onNativeEvent(event eventArg: PigeonConversationsNativeEvent, completion: @escaping () -> Void) {
    let channel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent", binaryMessenger: binaryMessenger, codec: codec)
    channel.sendMessage([eventArg] as [Any?]) { _ in
      completion()
    }
  }
}
