// Copyright (c) Twilio Flutter Conversations contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum ConversationsPigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


/// Client synchronization status mirrored from the Twilio Conversations SDK.
enum ClientSynchronizationStatus: Int, CaseIterable {
  case unknown = 0
  case started = 1
  case conversationsListCompleted = 2
  case completed = 3
  case failed = 4
}

/// Native client connection state.
enum ClientConnectionState: Int, CaseIterable {
  case unknown = 0
  case connecting = 1
  case connected = 2
  case disconnected = 3
  case denied = 4
  case error = 5
  case fatal = 6
}

/// Per-conversation synchronization state.
enum ConversationSynchronizationStatus: Int, CaseIterable {
  case unknown = 0
  case none = 1
  case identifier = 2
  case metadata = 3
  case syncWindow = 4
  case all = 5
  case failed = 6
}

/// Discriminator for events emitted from native code to Dart.
enum ConversationsEventType: Int, CaseIterable {
  case clientSynchronizationStatusUpdated = 0
  case connectionStateChanged = 1
  case conversationAdded = 2
  case conversationUpdated = 3
  case conversationDeleted = 4
  case conversationSynchronizationUpdated = 5
  case messageAdded = 6
  case messageUpdated = 7
  case messageDeleted = 8
  case participantAdded = 9
  case participantUpdated = 10
  case participantDeleted = 11
  case typingStarted = 12
  case typingEnded = 13
  case userUpdated = 14
  case userSubscribed = 15
  case userUnsubscribed = 16
  case tokenAboutToExpire = 17
  case tokenExpired = 18
  case notificationSubscribed = 19
  case error = 20
}

enum MessageContentType: Int, CaseIterable {
  case text = 0
  case media = 1
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConnectRequest: Hashable, CustomStringConvertible {
  var accessToken: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConnectRequest? {
    let accessToken = pigeonVar_list[0] as! String

    return ConnectRequest(
      accessToken: accessToken
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken
    ]
  }
  static func == (lhs: ConnectRequest, rhs: ConnectRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConnectRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
  }

  public var description: String {
    return "ConnectRequest(accessToken: \(String(describing: accessToken)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConversationDto: Hashable, CustomStringConvertible {
  var sid: String
  var uniqueName: String
  var friendlyName: String
  var lastMessageIndex: Int64? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConversationDto? {
    let sid = pigeonVar_list[0] as! String
    let uniqueName = pigeonVar_list[1] as! String
    let friendlyName = pigeonVar_list[2] as! String
    let lastMessageIndex: Int64? = nilOrValue(pigeonVar_list[3])

    return ConversationDto(
      sid: sid,
      uniqueName: uniqueName,
      friendlyName: friendlyName,
      lastMessageIndex: lastMessageIndex
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      uniqueName,
      friendlyName,
      lastMessageIndex,
    ]
  }
  static func == (lhs: ConversationDto, rhs: ConversationDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.uniqueName, rhs.uniqueName) && ConversationsPigeonPigeonInternal.deepEquals(lhs.friendlyName, rhs.friendlyName) && ConversationsPigeonPigeonInternal.deepEquals(lhs.lastMessageIndex, rhs.lastMessageIndex)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConversationDto")
    ConversationsPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: uniqueName, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: friendlyName, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: lastMessageIndex, hasher: &hasher)
  }

  public var description: String {
    return "ConversationDto(sid: \(String(describing: sid)), uniqueName: \(String(describing: uniqueName)), friendlyName: \(String(describing: friendlyName)), lastMessageIndex: \(String(describing: lastMessageIndex)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MediaAttachmentDto: Hashable, CustomStringConvertible {
  var sid: String
  var contentType: String
  var filename: String
  var sizeBytes: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MediaAttachmentDto? {
    let sid = pigeonVar_list[0] as! String
    let contentType = pigeonVar_list[1] as! String
    let filename = pigeonVar_list[2] as! String
    let sizeBytes = pigeonVar_list[3] as! Int64

    return MediaAttachmentDto(
      sid: sid,
      contentType: contentType,
      filename: filename,
      sizeBytes: sizeBytes
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      contentType,
      filename,
      sizeBytes,
    ]
  }
  static func == (lhs: MediaAttachmentDto, rhs: MediaAttachmentDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.contentType, rhs.contentType) && ConversationsPigeonPigeonInternal.deepEquals(lhs.filename, rhs.filename) && ConversationsPigeonPigeonInternal.deepEquals(lhs.sizeBytes, rhs.sizeBytes)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MediaAttachmentDto")
    ConversationsPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: contentType, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: filename, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: sizeBytes, hasher: &hasher)
  }

  public var description: String {
    return "MediaAttachmentDto(sid: \(String(describing: sid)), contentType: \(String(describing: contentType)), filename: \(String(describing: filename)), sizeBytes: \(String(describing: sizeBytes)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct MessageDto: Hashable, CustomStringConvertible {
  var sid: String
  var conversationSid: String
  var author: String
  var body: String
  var messageIndex: Int64
  var dateCreatedEpochMs: Int64
  var contentType: MessageContentType
  var mediaAttachments: [MediaAttachmentDto?]? = nil
  var attributesJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> MessageDto? {
    let sid = pigeonVar_list[0] as! String
    let conversationSid = pigeonVar_list[1] as! String
    let author = pigeonVar_list[2] as! String
    let body = pigeonVar_list[3] as! String
    let messageIndex = pigeonVar_list[4] as! Int64
    let dateCreatedEpochMs = pigeonVar_list[5] as! Int64
    let contentType = pigeonVar_list[6] as! MessageContentType
    let mediaAttachments: [MediaAttachmentDto?]? = nilOrValue(pigeonVar_list[7])
    let attributesJson: String? = nilOrValue(pigeonVar_list[8])

    return MessageDto(
      sid: sid,
      conversationSid: conversationSid,
      author: author,
      body: body,
      messageIndex: messageIndex,
      dateCreatedEpochMs: dateCreatedEpochMs,
      contentType: contentType,
      mediaAttachments: mediaAttachments,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      conversationSid,
      author,
      body,
      messageIndex,
      dateCreatedEpochMs,
      contentType,
      mediaAttachments,
      attributesJson,
    ]
  }
  static func == (lhs: MessageDto, rhs: MessageDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.author, rhs.author) && ConversationsPigeonPigeonInternal.deepEquals(lhs.body, rhs.body) && ConversationsPigeonPigeonInternal.deepEquals(lhs.messageIndex, rhs.messageIndex) && ConversationsPigeonPigeonInternal.deepEquals(lhs.dateCreatedEpochMs, rhs.dateCreatedEpochMs) && ConversationsPigeonPigeonInternal.deepEquals(lhs.contentType, rhs.contentType) && ConversationsPigeonPigeonInternal.deepEquals(lhs.mediaAttachments, rhs.mediaAttachments) && ConversationsPigeonPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("MessageDto")
    ConversationsPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: author, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: body, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: messageIndex, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: dateCreatedEpochMs, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: contentType, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: mediaAttachments, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
  }

  public var description: String {
    return "MessageDto(sid: \(String(describing: sid)), conversationSid: \(String(describing: conversationSid)), author: \(String(describing: author)), body: \(String(describing: body)), messageIndex: \(String(describing: messageIndex)), dateCreatedEpochMs: \(String(describing: dateCreatedEpochMs)), contentType: \(String(describing: contentType)), mediaAttachments: \(String(describing: mediaAttachments)), attributesJson: \(String(describing: attributesJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ParticipantDto: Hashable, CustomStringConvertible {
  var sid: String
  var identity: String
  var conversationSid: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ParticipantDto? {
    let sid = pigeonVar_list[0] as! String
    let identity = pigeonVar_list[1] as! String
    let conversationSid = pigeonVar_list[2] as! String

    return ParticipantDto(
      sid: sid,
      identity: identity,
      conversationSid: conversationSid
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      identity,
      conversationSid,
    ]
  }
  static func == (lhs: ParticipantDto, rhs: ParticipantDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.identity, rhs.identity) && ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ParticipantDto")
    ConversationsPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: identity, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
  }

  public var description: String {
    return "ParticipantDto(sid: \(String(describing: sid)), identity: \(String(describing: identity)), conversationSid: \(String(describing: conversationSid)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct UserDto: Hashable, CustomStringConvertible {
  var identity: String
  var friendlyName: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> UserDto? {
    let identity = pigeonVar_list[0] as! String
    let friendlyName: String? = nilOrValue(pigeonVar_list[1])

    return UserDto(
      identity: identity,
      friendlyName: friendlyName
    )
  }
  func toList() -> [Any?] {
    return [
      identity,
      friendlyName,
    ]
  }
  static func == (lhs: UserDto, rhs: UserDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.identity, rhs.identity) && ConversationsPigeonPigeonInternal.deepEquals(lhs.friendlyName, rhs.friendlyName)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("UserDto")
    ConversationsPigeonPigeonInternal.deepHash(value: identity, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: friendlyName, hasher: &hasher)
  }

  public var description: String {
    return "UserDto(identity: \(String(describing: identity)), friendlyName: \(String(describing: friendlyName)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendMessageRequest: Hashable, CustomStringConvertible {
  var conversationSid: String
  var body: String
  var attributesJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendMessageRequest? {
    let conversationSid = pigeonVar_list[0] as! String
    let body = pigeonVar_list[1] as! String
    let attributesJson: String? = nilOrValue(pigeonVar_list[2])

    return SendMessageRequest(
      conversationSid: conversationSid,
      body: body,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      body,
      attributesJson,
    ]
  }
  static func == (lhs: SendMessageRequest, rhs: SendMessageRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.body, rhs.body) && ConversationsPigeonPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SendMessageRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: body, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
  }

  public var description: String {
    return "SendMessageRequest(conversationSid: \(String(describing: conversationSid)), body: \(String(describing: body)), attributesJson: \(String(describing: attributesJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetMessagesRequest: Hashable, CustomStringConvertible {
  var conversationSid: String
  var count: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetMessagesRequest? {
    let conversationSid = pigeonVar_list[0] as! String
    let count = pigeonVar_list[1] as! Int64

    return GetMessagesRequest(
      conversationSid: conversationSid,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      count,
    ]
  }
  static func == (lhs: GetMessagesRequest, rhs: GetMessagesRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.count, rhs.count)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetMessagesRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: count, hasher: &hasher)
  }

  public var description: String {
    return "GetMessagesRequest(conversationSid: \(String(describing: conversationSid)), count: \(String(describing: count)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetMessagesBeforeRequest: Hashable, CustomStringConvertible {
  var conversationSid: String
  var beforeMessageIndex: Int64
  var count: Int64


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetMessagesBeforeRequest? {
    let conversationSid = pigeonVar_list[0] as! String
    let beforeMessageIndex = pigeonVar_list[1] as! Int64
    let count = pigeonVar_list[2] as! Int64

    return GetMessagesBeforeRequest(
      conversationSid: conversationSid,
      beforeMessageIndex: beforeMessageIndex,
      count: count
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      beforeMessageIndex,
      count,
    ]
  }
  static func == (lhs: GetMessagesBeforeRequest, rhs: GetMessagesBeforeRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.beforeMessageIndex, rhs.beforeMessageIndex) && ConversationsPigeonPigeonInternal.deepEquals(lhs.count, rhs.count)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetMessagesBeforeRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: beforeMessageIndex, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: count, hasher: &hasher)
  }

  public var description: String {
    return "GetMessagesBeforeRequest(conversationSid: \(String(describing: conversationSid)), beforeMessageIndex: \(String(describing: beforeMessageIndex)), count: \(String(describing: count)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct SendMediaMessageRequest: Hashable, CustomStringConvertible {
  var conversationSid: String
  var filePath: String
  var mimeType: String
  var filename: String
  var caption: String? = nil
  var attributesJson: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> SendMediaMessageRequest? {
    let conversationSid = pigeonVar_list[0] as! String
    let filePath = pigeonVar_list[1] as! String
    let mimeType = pigeonVar_list[2] as! String
    let filename = pigeonVar_list[3] as! String
    let caption: String? = nilOrValue(pigeonVar_list[4])
    let attributesJson: String? = nilOrValue(pigeonVar_list[5])

    return SendMediaMessageRequest(
      conversationSid: conversationSid,
      filePath: filePath,
      mimeType: mimeType,
      filename: filename,
      caption: caption,
      attributesJson: attributesJson
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      filePath,
      mimeType,
      filename,
      caption,
      attributesJson,
    ]
  }
  static func == (lhs: SendMediaMessageRequest, rhs: SendMediaMessageRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.filePath, rhs.filePath) && ConversationsPigeonPigeonInternal.deepEquals(lhs.mimeType, rhs.mimeType) && ConversationsPigeonPigeonInternal.deepEquals(lhs.filename, rhs.filename) && ConversationsPigeonPigeonInternal.deepEquals(lhs.caption, rhs.caption) && ConversationsPigeonPigeonInternal.deepEquals(lhs.attributesJson, rhs.attributesJson)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("SendMediaMessageRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: filePath, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: mimeType, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: filename, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: caption, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: attributesJson, hasher: &hasher)
  }

  public var description: String {
    return "SendMediaMessageRequest(conversationSid: \(String(describing: conversationSid)), filePath: \(String(describing: filePath)), mimeType: \(String(describing: mimeType)), filename: \(String(describing: filename)), caption: \(String(describing: caption)), attributesJson: \(String(describing: attributesJson)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct GetMediaTemporaryUrlRequest: Hashable, CustomStringConvertible {
  var conversationSid: String
  var messageIndex: Int64
  var mediaSid: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> GetMediaTemporaryUrlRequest? {
    let conversationSid = pigeonVar_list[0] as! String
    let messageIndex = pigeonVar_list[1] as! Int64
    let mediaSid = pigeonVar_list[2] as! String

    return GetMediaTemporaryUrlRequest(
      conversationSid: conversationSid,
      messageIndex: messageIndex,
      mediaSid: mediaSid
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid,
      messageIndex,
      mediaSid,
    ]
  }
  static func == (lhs: GetMediaTemporaryUrlRequest, rhs: GetMediaTemporaryUrlRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid) && ConversationsPigeonPigeonInternal.deepEquals(lhs.messageIndex, rhs.messageIndex) && ConversationsPigeonPigeonInternal.deepEquals(lhs.mediaSid, rhs.mediaSid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("GetMediaTemporaryUrlRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: messageIndex, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: mediaSid, hasher: &hasher)
  }

  public var description: String {
    return "GetMediaTemporaryUrlRequest(conversationSid: \(String(describing: conversationSid)), messageIndex: \(String(describing: messageIndex)), mediaSid: \(String(describing: mediaSid)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConversationRequest: Hashable, CustomStringConvertible {
  var conversationSid: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConversationRequest? {
    let conversationSid = pigeonVar_list[0] as! String

    return ConversationRequest(
      conversationSid: conversationSid
    )
  }
  func toList() -> [Any?] {
    return [
      conversationSid
    ]
  }
  static func == (lhs: ConversationRequest, rhs: ConversationRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSid, rhs.conversationSid)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConversationRequest")
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSid, hasher: &hasher)
  }

  public var description: String {
    return "ConversationRequest(conversationSid: \(String(describing: conversationSid)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct ConversationsNativeEvent: Hashable, CustomStringConvertible {
  var type: ConversationsEventType
  var synchronizationStatus: ClientSynchronizationStatus? = nil
  var connectionState: ClientConnectionState? = nil
  var conversationSyncStatus: ConversationSynchronizationStatus? = nil
  var conversation: ConversationDto? = nil
  var message: MessageDto? = nil
  var participant: ParticipantDto? = nil
  var user: UserDto? = nil
  var updateReason: String? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> ConversationsNativeEvent? {
    let type = pigeonVar_list[0] as! ConversationsEventType
    let synchronizationStatus: ClientSynchronizationStatus? = nilOrValue(pigeonVar_list[1])
    let connectionState: ClientConnectionState? = nilOrValue(pigeonVar_list[2])
    let conversationSyncStatus: ConversationSynchronizationStatus? = nilOrValue(pigeonVar_list[3])
    let conversation: ConversationDto? = nilOrValue(pigeonVar_list[4])
    let message: MessageDto? = nilOrValue(pigeonVar_list[5])
    let participant: ParticipantDto? = nilOrValue(pigeonVar_list[6])
    let user: UserDto? = nilOrValue(pigeonVar_list[7])
    let updateReason: String? = nilOrValue(pigeonVar_list[8])
    let errorCode: String? = nilOrValue(pigeonVar_list[9])
    let errorMessage: String? = nilOrValue(pigeonVar_list[10])

    return ConversationsNativeEvent(
      type: type,
      synchronizationStatus: synchronizationStatus,
      connectionState: connectionState,
      conversationSyncStatus: conversationSyncStatus,
      conversation: conversation,
      message: message,
      participant: participant,
      user: user,
      updateReason: updateReason,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      synchronizationStatus,
      connectionState,
      conversationSyncStatus,
      conversation,
      message,
      participant,
      user,
      updateReason,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: ConversationsNativeEvent, rhs: ConversationsNativeEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return ConversationsPigeonPigeonInternal.deepEquals(lhs.type, rhs.type) && ConversationsPigeonPigeonInternal.deepEquals(lhs.synchronizationStatus, rhs.synchronizationStatus) && ConversationsPigeonPigeonInternal.deepEquals(lhs.connectionState, rhs.connectionState) && ConversationsPigeonPigeonInternal.deepEquals(lhs.conversationSyncStatus, rhs.conversationSyncStatus) && ConversationsPigeonPigeonInternal.deepEquals(lhs.conversation, rhs.conversation) && ConversationsPigeonPigeonInternal.deepEquals(lhs.message, rhs.message) && ConversationsPigeonPigeonInternal.deepEquals(lhs.participant, rhs.participant) && ConversationsPigeonPigeonInternal.deepEquals(lhs.user, rhs.user) && ConversationsPigeonPigeonInternal.deepEquals(lhs.updateReason, rhs.updateReason) && ConversationsPigeonPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && ConversationsPigeonPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("ConversationsNativeEvent")
    ConversationsPigeonPigeonInternal.deepHash(value: type, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: synchronizationStatus, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: connectionState, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: conversationSyncStatus, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: conversation, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: message, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: participant, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: user, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: updateReason, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    ConversationsPigeonPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "ConversationsNativeEvent(type: \(String(describing: type)), synchronizationStatus: \(String(describing: synchronizationStatus)), connectionState: \(String(describing: connectionState)), conversationSyncStatus: \(String(describing: conversationSyncStatus)), conversation: \(String(describing: conversation)), message: \(String(describing: message)), participant: \(String(describing: participant)), user: \(String(describing: user)), updateReason: \(String(describing: updateReason)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class ConversationsPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ClientSynchronizationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ClientConnectionState(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConversationSynchronizationStatus(rawValue: enumResultAsInt)
      }
      return nil
    case 132:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return ConversationsEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 133:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return MessageContentType(rawValue: enumResultAsInt)
      }
      return nil
    case 134:
      return ConnectRequest.fromList(self.readValue() as! [Any?])
    case 135:
      return ConversationDto.fromList(self.readValue() as! [Any?])
    case 136:
      return MediaAttachmentDto.fromList(self.readValue() as! [Any?])
    case 137:
      return MessageDto.fromList(self.readValue() as! [Any?])
    case 138:
      return ParticipantDto.fromList(self.readValue() as! [Any?])
    case 139:
      return UserDto.fromList(self.readValue() as! [Any?])
    case 140:
      return SendMessageRequest.fromList(self.readValue() as! [Any?])
    case 141:
      return GetMessagesRequest.fromList(self.readValue() as! [Any?])
    case 142:
      return GetMessagesBeforeRequest.fromList(self.readValue() as! [Any?])
    case 143:
      return SendMediaMessageRequest.fromList(self.readValue() as! [Any?])
    case 144:
      return GetMediaTemporaryUrlRequest.fromList(self.readValue() as! [Any?])
    case 145:
      return ConversationRequest.fromList(self.readValue() as! [Any?])
    case 146:
      return ConversationsNativeEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class ConversationsPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? ClientSynchronizationStatus {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? ClientConnectionState {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConversationSynchronizationStatus {
      super.writeByte(131)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConversationsEventType {
      super.writeByte(132)
      super.writeValue(value.rawValue)
    } else if let value = value as? MessageContentType {
      super.writeByte(133)
      super.writeValue(value.rawValue)
    } else if let value = value as? ConnectRequest {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else if let value = value as? ConversationDto {
      super.writeByte(135)
      super.writeValue(value.toList())
    } else if let value = value as? MediaAttachmentDto {
      super.writeByte(136)
      super.writeValue(value.toList())
    } else if let value = value as? MessageDto {
      super.writeByte(137)
      super.writeValue(value.toList())
    } else if let value = value as? ParticipantDto {
      super.writeByte(138)
      super.writeValue(value.toList())
    } else if let value = value as? UserDto {
      super.writeByte(139)
      super.writeValue(value.toList())
    } else if let value = value as? SendMessageRequest {
      super.writeByte(140)
      super.writeValue(value.toList())
    } else if let value = value as? GetMessagesRequest {
      super.writeByte(141)
      super.writeValue(value.toList())
    } else if let value = value as? GetMessagesBeforeRequest {
      super.writeByte(142)
      super.writeValue(value.toList())
    } else if let value = value as? SendMediaMessageRequest {
      super.writeByte(143)
      super.writeValue(value.toList())
    } else if let value = value as? GetMediaTemporaryUrlRequest {
      super.writeByte(144)
      super.writeValue(value.toList())
    } else if let value = value as? ConversationRequest {
      super.writeByte(145)
      super.writeValue(value.toList())
    } else if let value = value as? ConversationsNativeEvent {
      super.writeByte(146)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class ConversationsPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return ConversationsPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return ConversationsPigeonPigeonCodecWriter(data: data)
  }
}

class ConversationsPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = ConversationsPigeonPigeonCodec(readerWriter: ConversationsPigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TwilioConversationsHostApi {
  func connect(request: ConnectRequest) async throws
  func disconnect() async throws
  func updateAccessToken(accessToken: String) async throws
  func sendMessage(request: SendMessageRequest) async throws -> MessageDto
  func listConversations() async throws -> [ConversationDto]
  func getConversation(sidOrUniqueName: String) async throws -> ConversationDto
  func getLastMessages(request: GetMessagesRequest) async throws -> [MessageDto]
  func getMessagesBefore(request: GetMessagesBeforeRequest) async throws -> [MessageDto]
  func sendMediaMessage(request: SendMediaMessageRequest) async throws -> MessageDto
  func getMediaTemporaryUrl(request: GetMediaTemporaryUrlRequest) async throws -> String
  func getParticipants(request: ConversationRequest) async throws -> [ParticipantDto]
  func sendTyping(request: ConversationRequest) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TwilioConversationsHostApiSetup {
  static var codec: FlutterStandardMessageCodec { ConversationsPigeonPigeonCodec.shared }
  /// Sets up an instance of `TwilioConversationsHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TwilioConversationsHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ConnectRequest
        Task { @MainActor in
          do {
            try await api.connect(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.disconnect()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let updateAccessTokenChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.updateAccessToken\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      updateAccessTokenChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let accessTokenArg = args[0] as! String
        Task { @MainActor in
          do {
            try await api.updateAccessToken(accessToken: accessTokenArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      updateAccessTokenChannel.setMessageHandler(nil)
    }
    let sendMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SendMessageRequest
        Task { @MainActor in
          do {
            let result = try await api.sendMessage(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMessageChannel.setMessageHandler(nil)
    }
    let listConversationsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.listConversations\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      listConversationsChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            let result = try await api.listConversations()
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      listConversationsChannel.setMessageHandler(nil)
    }
    let getConversationChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getConversation\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getConversationChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let sidOrUniqueNameArg = args[0] as! String
        Task { @MainActor in
          do {
            let result = try await api.getConversation(sidOrUniqueName: sidOrUniqueNameArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getConversationChannel.setMessageHandler(nil)
    }
    let getLastMessagesChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getLastMessages\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getLastMessagesChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GetMessagesRequest
        Task { @MainActor in
          do {
            let result = try await api.getLastMessages(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getLastMessagesChannel.setMessageHandler(nil)
    }
    let getMessagesBeforeChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMessagesBefore\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMessagesBeforeChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GetMessagesBeforeRequest
        Task { @MainActor in
          do {
            let result = try await api.getMessagesBefore(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMessagesBeforeChannel.setMessageHandler(nil)
    }
    let sendMediaMessageChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendMediaMessage\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendMediaMessageChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! SendMediaMessageRequest
        Task { @MainActor in
          do {
            let result = try await api.sendMediaMessage(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendMediaMessageChannel.setMessageHandler(nil)
    }
    let getMediaTemporaryUrlChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getMediaTemporaryUrl\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getMediaTemporaryUrlChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! GetMediaTemporaryUrlRequest
        Task { @MainActor in
          do {
            let result = try await api.getMediaTemporaryUrl(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getMediaTemporaryUrlChannel.setMessageHandler(nil)
    }
    let getParticipantsChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.getParticipants\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      getParticipantsChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ConversationRequest
        Task { @MainActor in
          do {
            let result = try await api.getParticipants(request: requestArg)
            reply(wrapResult(result))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      getParticipantsChannel.setMessageHandler(nil)
    }
    let sendTypingChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsHostApi.sendTyping\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      sendTypingChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! ConversationRequest
        Task { @MainActor in
          do {
            try await api.sendTyping(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      sendTypingChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TwilioConversationsFlutterApiProtocol {
  @MainActor func onNativeEvent(event eventArg: ConversationsNativeEvent) async throws
}
class TwilioConversationsFlutterApi: TwilioConversationsFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: ConversationsPigeonPigeonCodec {
    return ConversationsPigeonPigeonCodec.shared
  }
  @MainActor func onNativeEvent(event eventArg: ConversationsNativeEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.twilio_flutter_conversations.TwilioConversationsFlutterApi.onNativeEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
