// Copyright (c) Twilio Flutter Video contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
@file:Suppress("UNCHECKED_CAST", "ArrayInDataClass")

package com.twilioflutter.video.pigeon

import android.util.Log
import io.flutter.plugin.common.BasicMessageChannel
import io.flutter.plugin.common.BinaryMessenger
import io.flutter.plugin.common.EventChannel
import io.flutter.plugin.common.MessageCodec
import io.flutter.plugin.common.StandardMethodCodec
import io.flutter.plugin.common.StandardMessageCodec
import java.io.ByteArrayOutputStream
import java.nio.ByteBuffer
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.launch
import kotlinx.coroutines.suspendCancellableCoroutine
import kotlin.coroutines.resume
import kotlin.coroutines.resumeWithException
private object VideoPigeonPigeonUtils {

  fun createConnectionError(channelName: String): FlutterError {
    return FlutterError("channel-error",  "Unable to establish connection on channel: '$channelName'.", "")  }

  fun wrapResult(result: Any?): List<Any?> {
    return listOf(result)
  }

  fun wrapError(exception: Throwable): List<Any?> {
    return if (exception is FlutterError) {
      listOf(
        exception.code,
        exception.message,
        exception.details
      )
    } else {
      listOf(
        exception.javaClass.simpleName,
        exception.toString(),
        "Cause: " + exception.cause + ", Stacktrace: " + Log.getStackTraceString(exception)
      )
    }
  }
  fun doubleEquals(a: Double, b: Double): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0) 0.0 else a) == (if (b == 0.0) 0.0 else b) || (a.isNaN() && b.isNaN())
  }

  fun floatEquals(a: Float, b: Float): Boolean {
    // Normalize -0.0 to 0.0 and handle NaN equality.
    return (if (a == 0.0f) 0.0f else a) == (if (b == 0.0f) 0.0f else b) || (a.isNaN() && b.isNaN())
  }

  fun doubleHash(d: Double): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (d == 0.0) 0.0 else d
    val bits = java.lang.Double.doubleToLongBits(normalized)
    return (bits xor (bits ushr 32)).toInt()
  }

  fun floatHash(f: Float): Int {
    // Normalize -0.0 to 0.0 and handle NaN to ensure consistent hash codes.
    val normalized = if (f == 0.0f) 0.0f else f
    return java.lang.Float.floatToIntBits(normalized)
  }

  fun deepEquals(a: Any?, b: Any?): Boolean {
    if (a === b) {
      return true
    }
    if (a == null || b == null) {
      return false
    }
    if (a is ByteArray && b is ByteArray) {
      return a.contentEquals(b)
    }
    if (a is IntArray && b is IntArray) {
      return a.contentEquals(b)
    }
    if (a is LongArray && b is LongArray) {
      return a.contentEquals(b)
    }
    if (a is DoubleArray && b is DoubleArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!doubleEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is FloatArray && b is FloatArray) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!floatEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is Array<*> && b is Array<*>) {
      if (a.size != b.size) return false
      for (i in a.indices) {
        if (!deepEquals(a[i], b[i])) return false
      }
      return true
    }
    if (a is List<*> && b is List<*>) {
      if (a.size != b.size) return false
      val iterA = a.iterator()
      val iterB = b.iterator()
      while (iterA.hasNext() && iterB.hasNext()) {
        if (!deepEquals(iterA.next(), iterB.next())) return false
      }
      return true
    }
    if (a is Map<*, *> && b is Map<*, *>) {
      if (a.size != b.size) return false
      for (entry in a) {
        val key = entry.key
        var found = false
        for (bEntry in b) {
          if (deepEquals(key, bEntry.key)) {
            if (deepEquals(entry.value, bEntry.value)) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if (!found) return false
      }
      return true
    }
    if (a is Double && b is Double) {
      return doubleEquals(a, b)
    }
    if (a is Float && b is Float) {
      return floatEquals(a, b)
    }
    return a == b
  }

  fun deepHash(value: Any?): Int {
    return when (value) {
      null -> 0
      is ByteArray -> value.contentHashCode()
      is IntArray -> value.contentHashCode()
      is LongArray -> value.contentHashCode()
      is DoubleArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + doubleHash(item)
        }
        result
      }
      is FloatArray -> {
        var result = 1
        for (item in value) {
          result = 31 * result + floatHash(item)
        }
        result
      }
      is Array<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is List<*> -> {
        var result = 1
        for (item in value) {
          result = 31 * result + deepHash(item)
        }
        result
      }
      is Map<*, *> -> {
        var result = 0
        for (entry in value) {
          result += ((deepHash(entry.key) * 31) xor deepHash(entry.value))
        }
        result
      }
      is Double -> doubleHash(value)
      is Float -> floatHash(value)
      else -> value.hashCode()
    }
  }

}

/**
 * Error class for passing custom error details to Flutter via a thrown PlatformException.
 * @property code The error code.
 * @property message The error message.
 * @property details The error details. Must be a datatype supported by the api codec.
 */
class FlutterError (
  val code: String,
  override val message: String? = null,
  val details: Any? = null
) : RuntimeException()

enum class VideoRoomState(val raw: Int) {
  DISCONNECTED(0),
  CONNECTING(1),
  CONNECTED(2),
  RECONNECTING(3),
  DISCONNECTED_WITH_ERROR(4);

  companion object {
    fun ofRaw(raw: Int): VideoRoomState? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

enum class VideoEventType(val raw: Int) {
  ROOM_CONNECTED(0),
  ROOM_DISCONNECTED(1),
  ROOM_RECONNECTING(2),
  ROOM_RECONNECTED(3),
  PARTICIPANT_CONNECTED(4),
  PARTICIPANT_DISCONNECTED(5),
  DOMINANT_SPEAKER_CHANGED(6),
  ERROR(7);

  companion object {
    fun ofRaw(raw: Int): VideoEventType? {
      return values().firstOrNull { it.raw == raw }
    }
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoConnectRequest (
  val accessToken: String,
  val roomName: String,
  val enableAudio: Boolean,
  val enableVideo: Boolean
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoConnectRequest {
      val accessToken = pigeonVar_list[0] as String
      val roomName = pigeonVar_list[1] as String
      val enableAudio = pigeonVar_list[2] as Boolean
      val enableVideo = pigeonVar_list[3] as Boolean
      return VideoConnectRequest(accessToken, roomName, enableAudio, enableVideo)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      accessToken,
      roomName,
      enableAudio,
      enableVideo,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoConnectRequest
    return VideoPigeonPigeonUtils.deepEquals(this.accessToken, other.accessToken) && VideoPigeonPigeonUtils.deepEquals(this.roomName, other.roomName) && VideoPigeonPigeonUtils.deepEquals(this.enableAudio, other.enableAudio) && VideoPigeonPigeonUtils.deepEquals(this.enableVideo, other.enableVideo)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.accessToken)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.roomName)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.enableAudio)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.enableVideo)
    return result
  }
  override fun toString(): String {
    return "VideoConnectRequest(accessToken=$accessToken, roomName=$roomName, enableAudio=$enableAudio, enableVideo=$enableVideo)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoRoomDto (
  val sid: String,
  val name: String,
  val state: VideoRoomState
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoRoomDto {
      val sid = pigeonVar_list[0] as String
      val name = pigeonVar_list[1] as String
      val state = pigeonVar_list[2] as VideoRoomState
      return VideoRoomDto(sid, name, state)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      name,
      state,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoRoomDto
    return VideoPigeonPigeonUtils.deepEquals(this.sid, other.sid) && VideoPigeonPigeonUtils.deepEquals(this.name, other.name) && VideoPigeonPigeonUtils.deepEquals(this.state, other.state)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.name)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.state)
    return result
  }
  override fun toString(): String {
    return "VideoRoomDto(sid=$sid, name=$name, state=$state)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoParticipantDto (
  val sid: String,
  val identity: String
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoParticipantDto {
      val sid = pigeonVar_list[0] as String
      val identity = pigeonVar_list[1] as String
      return VideoParticipantDto(sid, identity)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      sid,
      identity,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoParticipantDto
    return VideoPigeonPigeonUtils.deepEquals(this.sid, other.sid) && VideoPigeonPigeonUtils.deepEquals(this.identity, other.identity)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.sid)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.identity)
    return result
  }
  override fun toString(): String {
    return "VideoParticipantDto(sid=$sid, identity=$identity)"
  }
}

/** Generated class from Pigeon that represents data sent in messages. */
data class VideoNativeEvent (
  val type: VideoEventType,
  val room: VideoRoomDto? = null,
  val participant: VideoParticipantDto? = null,
  val errorCode: String? = null,
  val errorMessage: String? = null
)
 {
  companion object {
    fun fromList(pigeonVar_list: List<Any?>): VideoNativeEvent {
      val type = pigeonVar_list[0] as VideoEventType
      val room = pigeonVar_list[1] as VideoRoomDto?
      val participant = pigeonVar_list[2] as VideoParticipantDto?
      val errorCode = pigeonVar_list[3] as String?
      val errorMessage = pigeonVar_list[4] as String?
      return VideoNativeEvent(type, room, participant, errorCode, errorMessage)
    }
  }
  fun toList(): List<Any?> {
    return listOf(
      type,
      room,
      participant,
      errorCode,
      errorMessage,
    )
  }
  override fun equals(other: Any?): Boolean {
    if (other == null || other.javaClass != javaClass) {
      return false
    }
    if (this === other) {
      return true
    }
    val other = other as VideoNativeEvent
    return VideoPigeonPigeonUtils.deepEquals(this.type, other.type) && VideoPigeonPigeonUtils.deepEquals(this.room, other.room) && VideoPigeonPigeonUtils.deepEquals(this.participant, other.participant) && VideoPigeonPigeonUtils.deepEquals(this.errorCode, other.errorCode) && VideoPigeonPigeonUtils.deepEquals(this.errorMessage, other.errorMessage)
  }

  override fun hashCode(): Int {
    var result = javaClass.hashCode()
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.type)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.room)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.participant)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.errorCode)
    result = 31 * result + VideoPigeonPigeonUtils.deepHash(this.errorMessage)
    return result
  }
  override fun toString(): String {
    return "VideoNativeEvent(type=$type, room=$room, participant=$participant, errorCode=$errorCode, errorMessage=$errorMessage)"
  }
}
private open class VideoPigeonPigeonCodec : StandardMessageCodec() {
  override fun readValueOfType(type: Byte, buffer: ByteBuffer): Any? {
    return when (type) {
      129.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoRoomState.ofRaw(it.toInt())
        }
      }
      130.toByte() -> {
        return (readValue(buffer) as Long?)?.let {
          VideoEventType.ofRaw(it.toInt())
        }
      }
      131.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoConnectRequest.fromList(it)
        }
      }
      132.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoRoomDto.fromList(it)
        }
      }
      133.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoParticipantDto.fromList(it)
        }
      }
      134.toByte() -> {
        return (readValue(buffer) as? List<Any?>)?.let {
          VideoNativeEvent.fromList(it)
        }
      }
      else -> super.readValueOfType(type, buffer)
    }
  }
  override fun writeValue(stream: ByteArrayOutputStream, value: Any?)   {
    when (value) {
      is VideoRoomState -> {
        stream.write(129)
        writeValue(stream, value.raw.toLong())
      }
      is VideoEventType -> {
        stream.write(130)
        writeValue(stream, value.raw.toLong())
      }
      is VideoConnectRequest -> {
        stream.write(131)
        writeValue(stream, value.toList())
      }
      is VideoRoomDto -> {
        stream.write(132)
        writeValue(stream, value.toList())
      }
      is VideoParticipantDto -> {
        stream.write(133)
        writeValue(stream, value.toList())
      }
      is VideoNativeEvent -> {
        stream.write(134)
        writeValue(stream, value.toList())
      }
      else -> super.writeValue(stream, value)
    }
  }
}


/** Generated interface from Pigeon that represents a handler of messages from Flutter. */
interface TwilioVideoHostApi {
  suspend fun connect(request: VideoConnectRequest)
  suspend fun disconnect()
  suspend fun setLocalAudioEnabled(enabled: Boolean)
  suspend fun setLocalVideoEnabled(enabled: Boolean)

  companion object {
    /** The codec used by TwilioVideoHostApi. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPigeonPigeonCodec()
    }
    /** Sets up an instance of `TwilioVideoHostApi` to handle messages through the `binaryMessenger`. */
    @JvmOverloads
    fun setUp(binaryMessenger: BinaryMessenger, api: TwilioVideoHostApi?, messageChannelSuffix: String = "") {
      val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.connect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val requestArg = args[0] as VideoConnectRequest
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.connect(requestArg)
                listOf(null)
              } catch (exception: Throwable) {
                VideoPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.disconnect$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { _, reply ->
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.disconnect()
                listOf(null)
              } catch (exception: Throwable) {
                VideoPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalAudioEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setLocalAudioEnabled(enabledArg)
                listOf(null)
              } catch (exception: Throwable) {
                VideoPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
      run {
        val channel = BasicMessageChannel<Any?>(binaryMessenger, "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalVideoEnabled$separatedMessageChannelSuffix", codec)
        if (api != null) {
          channel.setMessageHandler { message, reply ->
            val args = message as List<Any?>
            val enabledArg = args[0] as Boolean
            CoroutineScope(Dispatchers.Main).launch {
              val wrapped: List<Any?> = try {
                api.setLocalVideoEnabled(enabledArg)
                listOf(null)
              } catch (exception: Throwable) {
                VideoPigeonPigeonUtils.wrapError(exception)
              }
              reply.reply(wrapped)
            }
          }
        } else {
          channel.setMessageHandler(null)
        }
      }
    }
  }
}
/** Generated class from Pigeon that represents Flutter messages that can be called from Kotlin. */
class TwilioVideoFlutterApi(private val binaryMessenger: BinaryMessenger, private val messageChannelSuffix: String = "") {
  companion object {
    /** The codec used by TwilioVideoFlutterApi. */
    val codec: MessageCodec<Any?> by lazy {
      VideoPigeonPigeonCodec()
    }
  }
  suspend fun onNativeEvent(eventArg: VideoNativeEvent)
{
    val separatedMessageChannelSuffix = if (messageChannelSuffix.isNotEmpty()) ".$messageChannelSuffix" else ""
    return suspendCancellableCoroutine { continuation ->
      val channelName = "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoFlutterApi.onNativeEvent$separatedMessageChannelSuffix"
      val channel = BasicMessageChannel<Any?>(binaryMessenger, channelName, codec)
      channel.send(listOf(eventArg)) {
        if (it is List<*>) {
          if (it.size > 1) {
            continuation.resumeWithException(FlutterError(it[0] as String, it[1] as String, it[2] as String?))
          } else {
            continuation.resume(Unit)
          }
        } else {
          continuation.resumeWithException(VideoPigeonPigeonUtils.createConnectionError(channelName))
        } 
      }
    }
  }
}
