// Copyright (c) Twilio Flutter Video contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon
// ignore_for_file: unused_import, unused_shown_name
// ignore_for_file: type=lint

import 'dart:async';
import 'dart:typed_data' show Float64List, Int32List, Int64List;

import 'package:flutter/services.dart';
import 'package:meta/meta.dart' show immutable, protected, visibleForTesting;

Object? _extractReplyValueOrThrow(
    List<Object?>? replyList,
    String channelName, {
    required bool isNullValid,
}) {
  if (replyList == null) {
    throw PlatformException(
      code: 'channel-error',
      message: 'Unable to establish connection on channel: "$channelName".',
    );
  } else if (replyList.length > 1) {
    throw PlatformException(
      code: replyList[0]! as String,
      message: replyList[1] as String?,
      details: replyList[2],
    );
  } else if (!isNullValid && (replyList.isNotEmpty && replyList[0] == null)) {
    throw PlatformException(
      code: 'null-error',
      message: 'Host platform returned null value for non-null return value.',
    );
  }
  return replyList.firstOrNull;
}


List<Object?> wrapResponse({Object? result, PlatformException? error, bool empty = false}) {
  if (empty) {
    return <Object?>[];
  }
  if (error == null) {
    return <Object?>[result];
  }
  return <Object?>[error.code, error.message, error.details];
}
bool _deepEquals(Object? a, Object? b) {
  if (identical(a, b)) {
    return true;
  }
  if (a is double && b is double) {
    if (a.isNaN && b.isNaN) {
      return true;
    }
    return a == b;
  }
  if (a is List && b is List) {
    return a.length == b.length &&
        a.indexed
            .every(((int, dynamic) item) => _deepEquals(item.$2, b[item.$1]));
  }
  if (a is Map && b is Map) {
    if (a.length != b.length) {
      return false;
    }
    for (final MapEntry<Object?, Object?> entryA in a.entries) {
      bool found = false;
      for (final MapEntry<Object?, Object?> entryB in b.entries) {
        if (_deepEquals(entryA.key, entryB.key)) {
          if (_deepEquals(entryA.value, entryB.value)) {
            found = true;
            break;
          } else {
            return false;
          }
        }
      }
      if (!found) {
        return false;
      }
    }
    return true;
  }
  return a == b;
}

int _deepHash(Object? value) {
  if (value is List) {
    return Object.hashAll(value.map(_deepHash));
  }
  if (value is Map) {
    int result = 0;
    for (final MapEntry<Object?, Object?> entry in value.entries) {
      result += (_deepHash(entry.key) * 31) ^ _deepHash(entry.value);
    }
    return result;
  }
  if (value is double && value.isNaN) {
    // Normalize NaN to a consistent hash.
    return 0x7FF8000000000000.hashCode;
  }
  if (value is double && value == 0.0) {
    // Normalize -0.0 to 0.0 so they have the same hash code.
    return 0.0.hashCode;
  }
  return value.hashCode;
}


enum VideoRoomState {
  disconnected,
  connecting,
  connected,
  reconnecting,
  disconnectedWithError;
}

enum VideoEventType {
  roomConnected,
  roomDisconnected,
  roomReconnecting,
  roomReconnected,
  participantConnected,
  participantDisconnected,
  dominantSpeakerChanged,
  error;
}

class VideoConnectRequest {
  VideoConnectRequest({
    required this.accessToken,
    required this.roomName,
    this.enableAudio = true,
    this.enableVideo = true,
  });

  String accessToken;

  String roomName;

  bool enableAudio;

  bool enableVideo;

  List<Object?> _toList() {
    return <Object?>[
      accessToken,
      roomName,
      enableAudio,
      enableVideo,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoConnectRequest decode(Object result) {
    result as List<Object?>;
    return VideoConnectRequest(
      accessToken: result[0]! as String,
      roomName: result[1]! as String,
      enableAudio: result[2]! as bool,
      enableVideo: result[3]! as bool,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoConnectRequest || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(accessToken, other.accessToken) && _deepEquals(roomName, other.roomName) && _deepEquals(enableAudio, other.enableAudio) && _deepEquals(enableVideo, other.enableVideo);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoConnectRequest(accessToken: $accessToken, roomName: $roomName, enableAudio: $enableAudio, enableVideo: $enableVideo)';
  }
}

class VideoRoomDto {
  VideoRoomDto({
    required this.sid,
    required this.name,
    required this.state,
  });

  String sid;

  String name;

  VideoRoomState state;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      name,
      state,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoRoomDto decode(Object result) {
    result as List<Object?>;
    return VideoRoomDto(
      sid: result[0]! as String,
      name: result[1]! as String,
      state: result[2]! as VideoRoomState,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoRoomDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(name, other.name) && _deepEquals(state, other.state);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoRoomDto(sid: $sid, name: $name, state: $state)';
  }
}

class VideoParticipantDto {
  VideoParticipantDto({
    required this.sid,
    required this.identity,
  });

  String sid;

  String identity;

  List<Object?> _toList() {
    return <Object?>[
      sid,
      identity,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoParticipantDto decode(Object result) {
    result as List<Object?>;
    return VideoParticipantDto(
      sid: result[0]! as String,
      identity: result[1]! as String,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoParticipantDto || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(sid, other.sid) && _deepEquals(identity, other.identity);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoParticipantDto(sid: $sid, identity: $identity)';
  }
}

class VideoNativeEvent {
  VideoNativeEvent({
    required this.type,
    this.room,
    this.participant,
    this.errorCode,
    this.errorMessage,
  });

  VideoEventType type;

  VideoRoomDto? room;

  VideoParticipantDto? participant;

  String? errorCode;

  String? errorMessage;

  List<Object?> _toList() {
    return <Object?>[
      type,
      room,
      participant,
      errorCode,
      errorMessage,
    ];
  }

  Object encode() {
    return _toList();  }

  static VideoNativeEvent decode(Object result) {
    result as List<Object?>;
    return VideoNativeEvent(
      type: result[0]! as VideoEventType,
      room: result[1] as VideoRoomDto?,
      participant: result[2] as VideoParticipantDto?,
      errorCode: result[3] as String?,
      errorMessage: result[4] as String?,
    );
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  bool operator ==(Object other) {
    if (other is! VideoNativeEvent || other.runtimeType != runtimeType) {
      return false;
    }
    if (identical(this, other)) {
      return true;
    }
    return _deepEquals(type, other.type) && _deepEquals(room, other.room) && _deepEquals(participant, other.participant) && _deepEquals(errorCode, other.errorCode) && _deepEquals(errorMessage, other.errorMessage);
  }

  @override
  // ignore: avoid_equals_and_hash_code_on_mutable_classes
  int get hashCode => _deepHash(<Object?>[runtimeType, ..._toList()]);

  @override
  String toString() {
    return 'VideoNativeEvent(type: $type, room: $room, participant: $participant, errorCode: $errorCode, errorMessage: $errorMessage)';
  }
}


class _PigeonCodec extends StandardMessageCodec {
  const _PigeonCodec();
  @override
  void writeValue(WriteBuffer buffer, Object? value) {
    if (value is int) {
      buffer.putUint8(4);
      buffer.putInt64(value);
    }    else if (value is VideoRoomState) {
      buffer.putUint8(129);
      writeValue(buffer, value.index);
    }    else if (value is VideoEventType) {
      buffer.putUint8(130);
      writeValue(buffer, value.index);
    }    else if (value is VideoConnectRequest) {
      buffer.putUint8(131);
      writeValue(buffer, value.encode());
    }    else if (value is VideoRoomDto) {
      buffer.putUint8(132);
      writeValue(buffer, value.encode());
    }    else if (value is VideoParticipantDto) {
      buffer.putUint8(133);
      writeValue(buffer, value.encode());
    }    else if (value is VideoNativeEvent) {
      buffer.putUint8(134);
      writeValue(buffer, value.encode());
    } else {
      super.writeValue(buffer, value);
    }
  }

  @override
  Object? readValueOfType(int type, ReadBuffer buffer) {
    switch (type) {
      case 129:
        final value = readValue(buffer) as int?;
        return value == null ? null : VideoRoomState.values[value];
      case 130:
        final value = readValue(buffer) as int?;
        return value == null ? null : VideoEventType.values[value];
      case 131:
        return VideoConnectRequest.decode(readValue(buffer)!);
      case 132:
        return VideoRoomDto.decode(readValue(buffer)!);
      case 133:
        return VideoParticipantDto.decode(readValue(buffer)!);
      case 134:
        return VideoNativeEvent.decode(readValue(buffer)!);
      default:
        return super.readValueOfType(type, buffer);
    }
  }
}

class TwilioVideoHostApi {
  /// Constructor for [TwilioVideoHostApi]. The [binaryMessenger] named argument is
  /// available for dependency injection. If it is left null, the default
  /// BinaryMessenger will be used which routes to the host platform.
  TwilioVideoHostApi({
      BinaryMessenger? binaryMessenger, 
      String messageChannelSuffix = '', 
      })
      : pigeonVar_binaryMessenger = binaryMessenger,
        pigeonVar_messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';

  final BinaryMessenger? pigeonVar_binaryMessenger;
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  final String pigeonVar_messageChannelSuffix;


  Future<void> connect(VideoConnectRequest request) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.connect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[request]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> disconnect() async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.disconnect$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(null);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setLocalAudioEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalAudioEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }

  Future<void> setLocalVideoEnabled(bool enabled) async {
    final pigeonVar_channelName = 'dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalVideoEnabled$pigeonVar_messageChannelSuffix';
    final pigeonVar_channel = BasicMessageChannel<Object?>(
      pigeonVar_channelName,
      pigeonChannelCodec,
      binaryMessenger: pigeonVar_binaryMessenger,
    );
    final Future<Object?> pigeonVar_sendFuture = pigeonVar_channel.send(<Object?>[enabled]);
    final pigeonVar_replyList = await pigeonVar_sendFuture as List<Object?>?;

    _extractReplyValueOrThrow(
        pigeonVar_replyList,
        pigeonVar_channelName,
        isNullValid: true,
    )
    ;
  }
}

abstract class TwilioVideoFlutterApi {
  static const MessageCodec<Object?> pigeonChannelCodec = _PigeonCodec();

  void onNativeEvent(VideoNativeEvent event);

  static void setUp(TwilioVideoFlutterApi? api, {
    BinaryMessenger? binaryMessenger, 
    String messageChannelSuffix = '',
  }) 
{
    messageChannelSuffix = messageChannelSuffix.isNotEmpty ? '.$messageChannelSuffix' : '';
    {
      final pigeonVar_channel = BasicMessageChannel<Object?>(
          'dev.flutter.pigeon.twilio_flutter_video.TwilioVideoFlutterApi.onNativeEvent$messageChannelSuffix', pigeonChannelCodec,
          binaryMessenger: binaryMessenger);
      if (api == null) {
        pigeonVar_channel.setMessageHandler(null);
      } else {
        pigeonVar_channel.setMessageHandler((Object? message) async {
          final List<Object?> args = message! as List<Object?>;
          final VideoNativeEvent arg_event = args[0]! as VideoNativeEvent;
          try {
            api.onNativeEvent(arg_event);
            return wrapResponse(empty: true);
          } on PlatformException catch (e) {
            return wrapResponse(error: e);
          }          catch (e) {
            return wrapResponse(error: PlatformException(code: 'error', message: e.toString()));
          }
        });
      }
    }
  }
}
