// Copyright (c) Twilio Flutter Video contributors.
// Autogenerated from Pigeon (v29.0.2), do not edit directly.
// See also: https://pub.dev/packages/pigeon

import Foundation

#if os(iOS)
  import Flutter
#elseif os(macOS)
  import FlutterMacOS
#else
  #error("Unsupported platform.")
#endif

/// Error class for passing custom error details to Dart side.
final class PigeonError: Error {
  let code: String
  let message: String?
  let details: Sendable?

  init(code: String, message: String?, details: Sendable?) {
    self.code = code
    self.message = message
    self.details = details
  }

  var localizedDescription: String {
    return
      "PigeonError(code: \(code), message: \(message ?? "<nil>"), details: \(details ?? "<nil>"))"
  }
}

private func wrapResult(_ result: Any?) -> [Any?] {
  return [result]
}

private func wrapError(_ error: Any) -> [Any?] {
  if let pigeonError = error as? PigeonError {
    return [
      pigeonError.code,
      pigeonError.message,
      pigeonError.details,
    ]
  }
  if let flutterError = error as? FlutterError {
    return [
      flutterError.code,
      flutterError.message,
      flutterError.details,
    ]
  }
  return [
    "\(error)",
    "\(Swift.type(of: error))",
    "Stacktrace: \(Thread.callStackSymbols)",
  ]
}

private func createConnectionError(withChannelName channelName: String) -> PigeonError {
  return PigeonError(code: "channel-error", message: "Unable to establish connection on channel: '\(channelName)'.", details: "")
}

enum VideoPigeonPigeonInternal {
  static func isNullish(_ value: Any?) -> Bool {
    guard let innerValue = value else {
      return true
    }

    if case Optional<Any>.some(Optional<Any>.none) = value {
      return true
    }

    return innerValue is NSNull
  }
  static func doubleEquals(_ lhs: Double, _ rhs: Double) -> Bool {
    return (lhs.isNaN && rhs.isNaN) || lhs == rhs
  }

  static func doubleHash(_ value: Double, _ hasher: inout Hasher) {
    if value.isNaN {
      hasher.combine(0x7FF8000000000000)
    } else {
      // Normalize -0.0 to 0.0
      hasher.combine(value == 0 ? 0 : value)
    }
  }

  static func deepEquals(_ lhs: Any?, _ rhs: Any?) -> Bool {
    let cleanLhs = nilOrValue(lhs) as Any?
    let cleanRhs = nilOrValue(rhs) as Any?
    switch (cleanLhs, cleanRhs) {
    case (nil, nil):
      return true

    case (nil, _), (_, nil):
      return false

    case (let lhs as AnyObject, let rhs as AnyObject) where lhs === rhs:
      return true

    case is (Void, Void):
      return true

    case (let lhsArray, let rhsArray) as ([Double], [Double]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !doubleEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsArray, let rhsArray) as ([Any?], [Any?]):
      guard lhsArray.count == rhsArray.count else { return false }
      for (index, element) in lhsArray.enumerated() {
        if !deepEquals(element, rhsArray[index]) {
          return false
        }
      }
      return true

    case (let lhsDictionary, let rhsDictionary) as ([AnyHashable: Any?], [AnyHashable: Any?]):
      guard lhsDictionary.count == rhsDictionary.count else { return false }
      for (lhsKey, lhsValue) in lhsDictionary {
        var found = false
        for (rhsKey, rhsValue) in rhsDictionary {
          if deepEquals(lhsKey, rhsKey) {
            if deepEquals(lhsValue, rhsValue) {
              found = true
              break
            } else {
              return false
            }
          }
        }
        if !found { return false }
      }
      return true

    case (let lhs as Double, let rhs as Double):
      return doubleEquals(lhs, rhs)

    case (let lhsHashable, let rhsHashable) as (AnyHashable, AnyHashable):
      return lhsHashable == rhsHashable

    default:
      return false
    }
  }

  static func deepHash(value: Any?, hasher: inout Hasher) {
    let cleanValue = nilOrValue(value) as Any?
    if let cleanValue = cleanValue {
      if let doubleValue = cleanValue as? Double {
        doubleHash(doubleValue, &hasher)
      } else if let valueList = cleanValue as? [Any?] {
        for item in valueList {
          deepHash(value: item, hasher: &hasher)
        }
      } else if let valueList = cleanValue as? [Double] {
        for item in valueList {
          doubleHash(item, &hasher)
        }
      } else if let valueDict = cleanValue as? [AnyHashable: Any?] {
        var result = 0
        for (key, value) in valueDict {
          var entryKeyHasher = Hasher()
          deepHash(value: key, hasher: &entryKeyHasher)
          var entryValueHasher = Hasher()
          deepHash(value: value, hasher: &entryValueHasher)
          result = result &+ ((entryKeyHasher.finalize() &* 31) ^ entryValueHasher.finalize())
        }
        hasher.combine(result)
      } else if let hashableValue = cleanValue as? AnyHashable {
        hasher.combine(hashableValue)
      } else {
        hasher.combine(String(describing: cleanValue))
      }
    } else {
      hasher.combine(0)
    }
  }

}

private func nilOrValue<T>(_ value: Any?) -> T? {
  if value is NSNull { return nil }
  return value as! T?
}


enum VideoRoomState: Int, CaseIterable {
  case disconnected = 0
  case connecting = 1
  case connected = 2
  case reconnecting = 3
  case disconnectedWithError = 4
}

enum VideoEventType: Int, CaseIterable {
  case roomConnected = 0
  case roomDisconnected = 1
  case roomReconnecting = 2
  case roomReconnected = 3
  case participantConnected = 4
  case participantDisconnected = 5
  case dominantSpeakerChanged = 6
  case error = 7
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoConnectRequest: Hashable, CustomStringConvertible {
  var accessToken: String
  var roomName: String
  var enableAudio: Bool
  var enableVideo: Bool


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoConnectRequest? {
    let accessToken = pigeonVar_list[0] as! String
    let roomName = pigeonVar_list[1] as! String
    let enableAudio = pigeonVar_list[2] as! Bool
    let enableVideo = pigeonVar_list[3] as! Bool

    return VideoConnectRequest(
      accessToken: accessToken,
      roomName: roomName,
      enableAudio: enableAudio,
      enableVideo: enableVideo
    )
  }
  func toList() -> [Any?] {
    return [
      accessToken,
      roomName,
      enableAudio,
      enableVideo,
    ]
  }
  static func == (lhs: VideoConnectRequest, rhs: VideoConnectRequest) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPigeonPigeonInternal.deepEquals(lhs.accessToken, rhs.accessToken) && VideoPigeonPigeonInternal.deepEquals(lhs.roomName, rhs.roomName) && VideoPigeonPigeonInternal.deepEquals(lhs.enableAudio, rhs.enableAudio) && VideoPigeonPigeonInternal.deepEquals(lhs.enableVideo, rhs.enableVideo)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoConnectRequest")
    VideoPigeonPigeonInternal.deepHash(value: accessToken, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: roomName, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: enableAudio, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: enableVideo, hasher: &hasher)
  }

  public var description: String {
    return "VideoConnectRequest(accessToken: \(String(describing: accessToken)), roomName: \(String(describing: roomName)), enableAudio: \(String(describing: enableAudio)), enableVideo: \(String(describing: enableVideo)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoRoomDto: Hashable, CustomStringConvertible {
  var sid: String
  var name: String
  var state: VideoRoomState


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoRoomDto? {
    let sid = pigeonVar_list[0] as! String
    let name = pigeonVar_list[1] as! String
    let state = pigeonVar_list[2] as! VideoRoomState

    return VideoRoomDto(
      sid: sid,
      name: name,
      state: state
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      name,
      state,
    ]
  }
  static func == (lhs: VideoRoomDto, rhs: VideoRoomDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && VideoPigeonPigeonInternal.deepEquals(lhs.name, rhs.name) && VideoPigeonPigeonInternal.deepEquals(lhs.state, rhs.state)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoRoomDto")
    VideoPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: name, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: state, hasher: &hasher)
  }

  public var description: String {
    return "VideoRoomDto(sid: \(String(describing: sid)), name: \(String(describing: name)), state: \(String(describing: state)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoParticipantDto: Hashable, CustomStringConvertible {
  var sid: String
  var identity: String


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoParticipantDto? {
    let sid = pigeonVar_list[0] as! String
    let identity = pigeonVar_list[1] as! String

    return VideoParticipantDto(
      sid: sid,
      identity: identity
    )
  }
  func toList() -> [Any?] {
    return [
      sid,
      identity,
    ]
  }
  static func == (lhs: VideoParticipantDto, rhs: VideoParticipantDto) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPigeonPigeonInternal.deepEquals(lhs.sid, rhs.sid) && VideoPigeonPigeonInternal.deepEquals(lhs.identity, rhs.identity)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoParticipantDto")
    VideoPigeonPigeonInternal.deepHash(value: sid, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: identity, hasher: &hasher)
  }

  public var description: String {
    return "VideoParticipantDto(sid: \(String(describing: sid)), identity: \(String(describing: identity)))"
  }
}

/// Generated class from Pigeon that represents data sent in messages.
struct VideoNativeEvent: Hashable, CustomStringConvertible {
  var type: VideoEventType
  var room: VideoRoomDto? = nil
  var participant: VideoParticipantDto? = nil
  var errorCode: String? = nil
  var errorMessage: String? = nil


  // swift-format-ignore: AlwaysUseLowerCamelCase
  static func fromList(_ pigeonVar_list: [Any?]) -> VideoNativeEvent? {
    let type = pigeonVar_list[0] as! VideoEventType
    let room: VideoRoomDto? = nilOrValue(pigeonVar_list[1])
    let participant: VideoParticipantDto? = nilOrValue(pigeonVar_list[2])
    let errorCode: String? = nilOrValue(pigeonVar_list[3])
    let errorMessage: String? = nilOrValue(pigeonVar_list[4])

    return VideoNativeEvent(
      type: type,
      room: room,
      participant: participant,
      errorCode: errorCode,
      errorMessage: errorMessage
    )
  }
  func toList() -> [Any?] {
    return [
      type,
      room,
      participant,
      errorCode,
      errorMessage,
    ]
  }
  static func == (lhs: VideoNativeEvent, rhs: VideoNativeEvent) -> Bool {
    if Swift.type(of: lhs) != Swift.type(of: rhs) {
      return false
    }
    return VideoPigeonPigeonInternal.deepEquals(lhs.type, rhs.type) && VideoPigeonPigeonInternal.deepEquals(lhs.room, rhs.room) && VideoPigeonPigeonInternal.deepEquals(lhs.participant, rhs.participant) && VideoPigeonPigeonInternal.deepEquals(lhs.errorCode, rhs.errorCode) && VideoPigeonPigeonInternal.deepEquals(lhs.errorMessage, rhs.errorMessage)
  }

  func hash(into hasher: inout Hasher) {
    hasher.combine("VideoNativeEvent")
    VideoPigeonPigeonInternal.deepHash(value: type, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: room, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: participant, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: errorCode, hasher: &hasher)
    VideoPigeonPigeonInternal.deepHash(value: errorMessage, hasher: &hasher)
  }

  public var description: String {
    return "VideoNativeEvent(type: \(String(describing: type)), room: \(String(describing: room)), participant: \(String(describing: participant)), errorCode: \(String(describing: errorCode)), errorMessage: \(String(describing: errorMessage)))"
  }
}

private class VideoPigeonPigeonCodecReader: FlutterStandardReader {
  override func readValue(ofType type: UInt8) -> Any? {
    switch type {
    case 129:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VideoRoomState(rawValue: enumResultAsInt)
      }
      return nil
    case 130:
      let enumResultAsInt: Int? = nilOrValue(self.readValue() as! Int?)
      if let enumResultAsInt = enumResultAsInt {
        return VideoEventType(rawValue: enumResultAsInt)
      }
      return nil
    case 131:
      return VideoConnectRequest.fromList(self.readValue() as! [Any?])
    case 132:
      return VideoRoomDto.fromList(self.readValue() as! [Any?])
    case 133:
      return VideoParticipantDto.fromList(self.readValue() as! [Any?])
    case 134:
      return VideoNativeEvent.fromList(self.readValue() as! [Any?])
    default:
      return super.readValue(ofType: type)
    }
  }
}

private class VideoPigeonPigeonCodecWriter: FlutterStandardWriter {
  override func writeValue(_ value: Any) {
    if let value = value as? VideoRoomState {
      super.writeByte(129)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoEventType {
      super.writeByte(130)
      super.writeValue(value.rawValue)
    } else if let value = value as? VideoConnectRequest {
      super.writeByte(131)
      super.writeValue(value.toList())
    } else if let value = value as? VideoRoomDto {
      super.writeByte(132)
      super.writeValue(value.toList())
    } else if let value = value as? VideoParticipantDto {
      super.writeByte(133)
      super.writeValue(value.toList())
    } else if let value = value as? VideoNativeEvent {
      super.writeByte(134)
      super.writeValue(value.toList())
    } else {
      super.writeValue(value)
    }
  }
}

private class VideoPigeonPigeonCodecReaderWriter: FlutterStandardReaderWriter {
  override func reader(with data: Data) -> FlutterStandardReader {
    return VideoPigeonPigeonCodecReader(data: data)
  }

  override func writer(with data: NSMutableData) -> FlutterStandardWriter {
    return VideoPigeonPigeonCodecWriter(data: data)
  }
}

class VideoPigeonPigeonCodec: FlutterStandardMessageCodec, @unchecked Sendable {
  static let shared = VideoPigeonPigeonCodec(readerWriter: VideoPigeonPigeonCodecReaderWriter())
}


/// Generated protocol from Pigeon that represents a handler of messages from Flutter.
protocol TwilioVideoHostApi {
  func connect(request: VideoConnectRequest) async throws
  func disconnect() async throws
  func setLocalAudioEnabled(enabled: Bool) async throws
  func setLocalVideoEnabled(enabled: Bool) async throws
}

/// Generated setup class from Pigeon to handle messages through the `binaryMessenger`.
class TwilioVideoHostApiSetup {
  static var codec: FlutterStandardMessageCodec { VideoPigeonPigeonCodec.shared }
  /// Sets up an instance of `TwilioVideoHostApi` to handle messages through the `binaryMessenger`.
  static func setUp(binaryMessenger: FlutterBinaryMessenger, api: TwilioVideoHostApi?, messageChannelSuffix: String = "") {
    let channelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
    let connectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.connect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      connectChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let requestArg = args[0] as! VideoConnectRequest
        Task { @MainActor in
          do {
            try await api.connect(request: requestArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      connectChannel.setMessageHandler(nil)
    }
    let disconnectChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.disconnect\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      disconnectChannel.setMessageHandler { _, reply in
        Task { @MainActor in
          do {
            try await api.disconnect()
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      disconnectChannel.setMessageHandler(nil)
    }
    let setLocalAudioEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalAudioEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocalAudioEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        Task { @MainActor in
          do {
            try await api.setLocalAudioEnabled(enabled: enabledArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLocalAudioEnabledChannel.setMessageHandler(nil)
    }
    let setLocalVideoEnabledChannel = FlutterBasicMessageChannel(name: "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoHostApi.setLocalVideoEnabled\(channelSuffix)", binaryMessenger: binaryMessenger, codec: codec)
    if let api = api {
      setLocalVideoEnabledChannel.setMessageHandler { message, reply in
        let args = message as! [Any?]
        let enabledArg = args[0] as! Bool
        Task { @MainActor in
          do {
            try await api.setLocalVideoEnabled(enabled: enabledArg)
            reply(wrapResult(nil))
          } catch {
            reply(wrapError(error))
          }
        }
      }
    } else {
      setLocalVideoEnabledChannel.setMessageHandler(nil)
    }
  }
}

/// Generated protocol from Pigeon that represents Flutter messages that can be called from Swift.
protocol TwilioVideoFlutterApiProtocol {
  @MainActor func onNativeEvent(event eventArg: VideoNativeEvent) async throws
}
class TwilioVideoFlutterApi: TwilioVideoFlutterApiProtocol {
  private let binaryMessenger: FlutterBinaryMessenger
  private let messageChannelSuffix: String
  init(binaryMessenger: FlutterBinaryMessenger, messageChannelSuffix: String = "") {
    self.binaryMessenger = binaryMessenger
    self.messageChannelSuffix = messageChannelSuffix.count > 0 ? ".\(messageChannelSuffix)" : ""
  }
  var codec: VideoPigeonPigeonCodec {
    return VideoPigeonPigeonCodec.shared
  }
  @MainActor func onNativeEvent(event eventArg: VideoNativeEvent) async throws {
    return try await withCheckedThrowingContinuation { continuation in
      let channelName: String = "dev.flutter.pigeon.twilio_flutter_video.TwilioVideoFlutterApi.onNativeEvent\(messageChannelSuffix)"
      let channel = FlutterBasicMessageChannel(name: channelName, binaryMessenger: binaryMessenger, codec: codec)
      channel.sendMessage([eventArg] as [Any?]) { response in
        guard let listResponse = response as? [Any?] else {
          continuation.resume(throwing: createConnectionError(withChannelName: channelName))
          return
        }
        if listResponse.count > 1 {
          let code: String = listResponse[0] as! String
          let message: String? = nilOrValue(listResponse[1])
          let details: String? = nilOrValue(listResponse[2])
          continuation.resume(throwing: PigeonError(code: code, message: message, details: details))
        } else {
          continuation.resume()
        }
      }
    }
  }
}
